import { useEffect, useMemo, useState } from 'react'
import DashboardLayout from '../../layouts/DashboardLayout'
import './Settings.css'

const blank={currentPassword:'',newPassword:'',confirmPassword:''}
const rules=p=>[['At least 8 characters',p.length>=8],['Uppercase letter',/[A-Z]/.test(p)],['Lowercase letter',/[a-z]/.test(p)],['Number',/\d/.test(p)],['Special character',/[^A-Za-z0-9]/.test(p)]]

export default function Settings(){
 const[open,setOpen]=useState(false),[values,setValues]=useState(blank),[visible,setVisible]=useState({}),[errors,setErrors]=useState({}),[submitting,setSubmitting]=useState(false),[notice,setNotice]=useState(''),[noticeType,setNoticeType]=useState(''),[currentUser,setCurrentUser]=useState({password:'Admin@123'})
 useEffect(()=>{if(noticeType!=='success')return;const timer=setTimeout(()=>setNotice(''),2000);return()=>clearTimeout(timer)},[noticeType])
 const requirements=useMemo(()=>rules(values.newPassword),[values.newPassword]);const met=requirements.filter(x=>x[1]).length;const strength=!values.newPassword?'Not set':['Weak','Fair','Good','Strong'][Math.max(0,met-2)]||'Strong'
 const validate=(data=values)=>{const e={},nextRules=rules(data.newPassword),nextMet=nextRules.filter(x=>x[1]).length;if(!data.currentPassword)e.currentPassword='Current password is required.';else if(data.currentPassword!==currentUser.password)e.currentPassword='Current password is incorrect.';if(!data.newPassword)e.newPassword='New password is required.';else if(nextMet<5)e.newPassword='Use all password requirements below.';else if(data.newPassword===data.currentPassword)e.newPassword='New password must be different from your current password.';if(!data.confirmPassword)e.confirmPassword='Confirm your new password.';else if(data.confirmPassword!==data.newPassword)e.confirmPassword='Passwords do not match.';return e}
 const update=e=>{const next={...values,[e.target.name]:e.target.value};setValues(next);setErrors(validate(next));setNotice('');setNoticeType('')}
 const handleChangePassword=async e=>{e.preventDefault();const next=validate();setErrors(next);if(Object.keys(next).length)return;setSubmitting(true);await new Promise(resolve=>setTimeout(resolve,650));setCurrentUser({password:values.newPassword});setValues(blank);setErrors({});setNoticeType('success');setNotice('Password changed successfully.');setSubmitting(false)}
 const close=()=>{setOpen(false);setValues(blank);setErrors({});setNotice('');setNoticeType('')}
 const field=(name,label)=><label className="settings-field"><span>{label} <b>*</b></span><div><input id={name} name={name} type={visible[name]?'text':'password'} value={values[name]} onChange={update} autoComplete={name==='currentPassword'?'current-password':'new-password'} aria-invalid={!!errors[name]} aria-describedby={errors[name]?`${name}-error`:undefined}/><button type="button" onClick={()=>setVisible(v=>({...v,[name]:!v[name]}))} aria-label={`${visible[name]?'Hide':'Show'} ${label}`}>{visible[name]?'Hide':'Show'}</button></div>{errors[name]&&<small id={`${name}-error`} role="alert">{errors[name]}</small>}</label>
 return <DashboardLayout><main className="settings-page"><header><p>Account</p><h1>Settings</h1><span>Manage your account preferences and security.</span></header><section className="settings-card"><h2>Account Preferences</h2><p>Additional notification and appearance preferences can be configured when their services are available.</p></section><section className="settings-card security"><div><p>Security</p><h2>Password &amp; Security</h2><span>Change your password to keep your account secure.</span></div><button className="settings-button" onClick={()=>setOpen(true)}>Change Password</button></section>{open&&<section className="settings-card password-card"><button className="close" onClick={close} aria-label="Close change password form">×</button><p>Security</p><h2>Change Password</h2><span>Create a strong, unique password for your account.</span><form onSubmit={handleChangePassword} noValidate>{field('currentPassword','Current Password')}{field('newPassword','New Password')}<div className="strength"><div><span>Password strength</span><b>{strength}</b></div><i className={`level-${met}`}/><ul>{requirements.map(x=><li className={x[1]?'met':''} key={x[0]}>{x[1]?'✓':'○'} {x[0]}</li>)}</ul></div>{field('confirmPassword','Confirm New Password')}{notice&&<div className={`notice ${noticeType}`} role="alert">{notice}</div>}<footer><button type="button" onClick={close}>Cancel</button><button className="settings-button" disabled={submitting||Object.keys(validate()).length>0}>{submitting?'Changing Password...':'Change Password'}</button></footer></form></section>}</main></DashboardLayout>
}
