USE cms_btech;
DELIMITER $$
DROP PROCEDURE IF EXISTS sp_cms_export$$
CREATE PROCEDURE sp_cms_export(IN p_screen VARCHAR(50),IN p_search VARCHAR(255),IN p_status VARCHAR(50),IN p_college_id BIGINT,IN p_department_id BIGINT,IN p_course_id BIGINT,IN p_branch_id BIGINT,IN p_semester_id BIGINT,IN p_academic_year_id BIGINT)
BEGIN
IF p_screen='colleges' THEN
SELECT * FROM (SELECT t.`college_id` AS `CollegeId`, t.`college_code` AS `CollegeCode`, t.`college_name` AS `CollegeName`, t.`college_type` AS `CollegeType`, t.`university_name` AS `UniversityName`, t.`email` AS `Email`, t.`mobile` AS `Mobile`, t.`phone` AS `Phone`, t.`principal` AS `Principal`, t.`principal_email` AS `PrincipalEmail`, t.`principal_contact` AS `PrincipalContact`, t.`alternate_contact_number` AS `AlternateContactNumber`, t.`accreditation_status` AS `AccreditationStatus`, t.`accreditation_body` AS `AccreditationBody`, t.`accreditation_grade` AS `AccreditationGrade`, t.`accreditation_number` AS `AccreditationNumber`, t.`valid_from` AS `ValidFrom`, t.`valid_until` AS `ValidUntil`, t.`address_line1` AS `AddressLine1`, t.`address_line2` AS `AddressLine2`, t.`city` AS `City`, t.`area` AS `Area`, t.`district` AS `District`, t.`state` AS `State`, t.`country` AS `Country`, t.`pincode` AS `Pincode`, t.`website` AS `Website`, t.`academic_year_id` AS `AcademicYearId`, t.`timezone` AS `Timezone`, t.`currency_code` AS `CurrencyCode`, t.`logo_path` AS `LogoPath`, t.`status` AS `Status`, t.`created_at` AS `CreatedAt`, t.`created_by` AS `CreatedBy`, t.`updated_at` AS `UpdatedAt`, t.`updated_by` AS `UpdatedBy`, t.`deleted_at` AS `DeletedAt`, t.`deleted_by` AS `DeletedBy` FROM `colleges` t  WHERE t.deleted_at IS NULL) q WHERE (p_college_id IS NULL OR q.`CollegeId`=p_college_id) AND (p_academic_year_id IS NULL OR q.`AcademicYearId`=p_academic_year_id) AND (p_status IS NULL OR LOWER(CAST(q.Status AS CHAR))=LOWER(p_status)) AND (NULLIF(p_search,'') IS NULL OR CONCAT_WS(' ',q.`CollegeCode`,q.`CollegeName`,q.`UniversityName`,q.`Email`,q.`PrincipalEmail`,q.`CurrencyCode`) LIKE CONCAT('%',p_search,'%')) LIMIT 100001;
ELSEIF p_screen='college-settings' THEN
SELECT * FROM (SELECT t.`college_setting_id` AS `CollegeSettingId`, t.`college_id` AS `CollegeId`, t.`college_name` AS `CollegeName`, t.`college_code` AS `CollegeCode`, t.`college_email` AS `CollegeEmail`, t.`phone_number` AS `PhoneNumber`, t.`website` AS `Website`, t.`address_line1` AS `AddressLine1`, t.`address_line2` AS `AddressLine2`, t.`city` AS `City`, t.`state` AS `State`, t.`pincode` AS `Pincode`, t.`academic_year` AS `AcademicYear`, t.`semester` AS `Semester`, t.`institution_type` AS `InstitutionType`, t.`date_format` AS `DateFormat`, t.`time_zone` AS `TimeZone`, t.`status` AS `Status`, t.`created_at` AS `CreatedAt`, t.`created_by` AS `CreatedBy`, t.`updated_at` AS `UpdatedAt`, t.`updated_by` AS `UpdatedBy` FROM `college_settings` t  WHERE 1=1) q WHERE (p_college_id IS NULL OR q.`CollegeId`=p_college_id) AND (p_status IS NULL OR LOWER(CAST(q.Status AS CHAR))=LOWER(p_status)) AND (NULLIF(p_search,'') IS NULL OR CONCAT_WS(' ',q.`CollegeName`,q.`CollegeCode`,q.`CollegeEmail`) LIKE CONCAT('%',p_search,'%')) LIMIT 100001;
ELSEIF p_screen='academic-years' THEN
SELECT * FROM (SELECT t.`academic_year_id` AS `AcademicYearId`, t.`academic_year_name` AS `AcademicYearName`, t.`start_date` AS `StartDate`, t.`end_date` AS `EndDate`, t.`status` AS `Status`, t.`is_archived` AS `IsArchived`, t.`created_at` AS `CreatedAt`, t.`created_by` AS `CreatedBy`, t.`updated_at` AS `UpdatedAt`, t.`updated_by` AS `UpdatedBy`, t.`deleted_at` AS `DeletedAt`, t.`deleted_by` AS `DeletedBy`, t.`active_guard` AS `ActiveGuard` FROM `academicyears` t  WHERE t.deleted_at IS NULL) q WHERE (p_academic_year_id IS NULL OR q.`AcademicYearId`=p_academic_year_id) AND (p_status IS NULL OR LOWER(CAST(q.Status AS CHAR))=LOWER(p_status)) AND (NULLIF(p_search,'') IS NULL OR CONCAT_WS(' ',q.`AcademicYearName`) LIKE CONCAT('%',p_search,'%')) LIMIT 100001;
ELSEIF p_screen='academic-levels' THEN
SELECT * FROM (SELECT t.`academic_level_id` AS `AcademicLevelId`, t.`academic_year_id` AS `AcademicYearId`, t.`level_type` AS `LevelType`, t.`level_name` AS `LevelName`, t.`level_number` AS `LevelNumber`, t.`status` AS `Status`, t.`created_at` AS `CreatedAt`, t.`created_by` AS `CreatedBy`, t.`updated_at` AS `UpdatedAt`, t.`updated_by` AS `UpdatedBy` FROM `academic_levels` t  WHERE 1=1) q WHERE (p_academic_year_id IS NULL OR q.`AcademicYearId`=p_academic_year_id) AND (p_status IS NULL OR LOWER(CAST(q.Status AS CHAR))=LOWER(p_status)) AND (NULLIF(p_search,'') IS NULL OR CONCAT_WS(' ',q.`LevelName`) LIKE CONCAT('%',p_search,'%')) LIMIT 100001;
ELSEIF p_screen='departments' THEN
SELECT * FROM (SELECT t.`department_id` AS `DepartmentId`, t.`college_id` AS `CollegeId`, t.`department_code` AS `DepartmentCode`, t.`department_name` AS `DepartmentName`, t.`description` AS `Description`, t.`status` AS `Status`, t.`created_at` AS `CreatedAt`, t.`created_by` AS `CreatedBy`, t.`updated_at` AS `UpdatedAt`, t.`updated_by` AS `UpdatedBy`, t.`deleted_at` AS `DeletedAt`, t.`deleted_by` AS `DeletedBy`, t.`hod_user_id` AS `HodUserId`, c.college_name AS `CollegeName` FROM `departments` t LEFT JOIN colleges c ON c.college_id=t.college_id WHERE t.deleted_at IS NULL) q WHERE (p_college_id IS NULL OR q.`CollegeId`=p_college_id) AND (p_department_id IS NULL OR q.`DepartmentId`=p_department_id) AND (p_status IS NULL OR LOWER(CAST(q.Status AS CHAR))=LOWER(p_status)) AND (NULLIF(p_search,'') IS NULL OR CONCAT_WS(' ',q.`DepartmentCode`,q.`DepartmentName`,q.`CollegeName`) LIKE CONCAT('%',p_search,'%')) LIMIT 100001;
ELSEIF p_screen='courses' THEN
SELECT * FROM (SELECT t.`course_id` AS `CourseId`, t.`college_id` AS `CollegeId`, t.`department_id` AS `DepartmentId`, t.`course_code` AS `CourseCode`, t.`course_name` AS `CourseName`, t.`course_short_name` AS `CourseShortName`, t.`course_type` AS `CourseType`, t.`duration_years` AS `DurationYears`, t.`total_semesters` AS `TotalSemesters`, t.`eligibility` AS `Eligibility`, t.`description` AS `Description`, t.`status` AS `Status`, t.`created_at` AS `CreatedAt`, t.`created_by` AS `CreatedBy`, t.`updated_at` AS `UpdatedAt`, t.`updated_by` AS `UpdatedBy`, t.`deleted_at` AS `DeletedAt`, t.`deleted_by` AS `DeletedBy`, d.department_name AS `DepartmentName` FROM `courses` t LEFT JOIN departments d ON d.department_id=t.department_id WHERE t.deleted_at IS NULL) q WHERE (p_college_id IS NULL OR q.`CollegeId`=p_college_id) AND (p_department_id IS NULL OR q.`DepartmentId`=p_department_id) AND (p_course_id IS NULL OR q.`CourseId`=p_course_id) AND (p_status IS NULL OR LOWER(CAST(q.Status AS CHAR))=LOWER(p_status)) AND (NULLIF(p_search,'') IS NULL OR CONCAT_WS(' ',q.`CourseCode`,q.`CourseName`,q.`CourseShortName`,q.`DepartmentName`) LIKE CONCAT('%',p_search,'%')) LIMIT 100001;
ELSEIF p_screen='branches' THEN
SELECT * FROM (SELECT t.`branch_id` AS `BranchId`, t.`course_id` AS `CourseId`, t.`branch_code` AS `BranchCode`, t.`branch_name` AS `BranchName`, t.`short_name` AS `ShortName`, t.`specialization` AS `Specialization`, t.`department_id` AS `DepartmentId`, t.`branch_type` AS `BranchType`, t.`duration` AS `Duration`, t.`total_semesters` AS `TotalSemesters`, t.`intake_capacity` AS `IntakeCapacity`, t.`starting_academic_year_id` AS `StartingAcademicYearId`, t.`description` AS `Description`, t.`status` AS `Status`, t.`created_at` AS `CreatedAt`, t.`created_by` AS `CreatedBy`, t.`updated_at` AS `UpdatedAt`, t.`updated_by` AS `UpdatedBy`, t.`deleted_at` AS `DeletedAt`, t.`deleted_by` AS `DeletedBy`, c.college_id AS `CollegeId`, c.course_name AS `CourseName`, d.department_name AS `DepartmentName` FROM `branches` t JOIN courses c ON c.course_id=t.course_id LEFT JOIN departments d ON d.department_id=t.department_id WHERE t.deleted_at IS NULL) q WHERE (p_college_id IS NULL OR q.`CollegeId`=p_college_id) AND (p_department_id IS NULL OR q.`DepartmentId`=p_department_id) AND (p_course_id IS NULL OR q.`CourseId`=p_course_id) AND (p_branch_id IS NULL OR q.`BranchId`=p_branch_id) AND (p_status IS NULL OR LOWER(CAST(q.Status AS CHAR))=LOWER(p_status)) AND (NULLIF(p_search,'') IS NULL OR CONCAT_WS(' ',q.`BranchCode`,q.`BranchName`,q.`ShortName`,q.`CourseName`,q.`DepartmentName`) LIKE CONCAT('%',p_search,'%')) LIMIT 100001;
ELSEIF p_screen='semesters' THEN
SELECT * FROM (SELECT t.`semester_id` AS `SemesterId`, t.`course_id` AS `CourseId`, t.`branch_id` AS `BranchId`, t.`semester_number` AS `SemesterNumber`, t.`year_number` AS `YearNumber`, t.`semester_name` AS `SemesterName`, t.`status` AS `Status`, t.`is_archived` AS `IsArchived`, t.`created_at` AS `CreatedAt`, t.`created_by` AS `CreatedBy`, t.`updated_at` AS `UpdatedAt`, t.`updated_by` AS `UpdatedBy`, t.`academic_year_id` AS `AcademicYearId`, t.`start_date` AS `StartDate`, t.`end_date` AS `EndDate`, c.college_id AS `CollegeId`, c.course_name AS `CourseName`, c.department_id AS `DepartmentId`, b.branch_name AS `BranchName` FROM `semesters` t JOIN courses c ON c.course_id=t.course_id JOIN branches b ON b.branch_id=t.branch_id WHERE t.is_archived=0) q WHERE (p_college_id IS NULL OR q.`CollegeId`=p_college_id) AND (p_department_id IS NULL OR q.`DepartmentId`=p_department_id) AND (p_course_id IS NULL OR q.`CourseId`=p_course_id) AND (p_branch_id IS NULL OR q.`BranchId`=p_branch_id) AND (p_semester_id IS NULL OR q.`SemesterId`=p_semester_id) AND (p_academic_year_id IS NULL OR q.`AcademicYearId`=p_academic_year_id) AND (p_status IS NULL OR LOWER(CAST(q.Status AS CHAR))=LOWER(p_status)) AND (NULLIF(p_search,'') IS NULL OR CONCAT_WS(' ',q.`SemesterName`,q.`CourseName`,q.`BranchName`) LIKE CONCAT('%',p_search,'%')) LIMIT 100001;
ELSEIF p_screen='sections' THEN
SELECT * FROM (SELECT t.`section_id` AS `SectionId`, t.`college_id` AS `CollegeId`, t.`academic_year_id` AS `AcademicYearId`, t.`department_id` AS `DepartmentId`, t.`course_id` AS `CourseId`, t.`branch_id` AS `BranchId`, t.`semester` AS `Semester`, t.`semester_id` AS `SemesterId`, t.`section_code` AS `SectionCode`, t.`section_name` AS `SectionName`, t.`capacity` AS `Capacity`, t.`class_teacher_employee_profile_id` AS `ClassTeacherEmployeeProfileId`, t.`room` AS `Room`, t.`shift` AS `Shift`, t.`section_type` AS `SectionType`, t.`status` AS `Status`, t.`is_archived` AS `IsArchived`, t.`created_at` AS `CreatedAt`, t.`created_by` AS `CreatedBy`, t.`updated_at` AS `UpdatedAt`, t.`updated_by` AS `UpdatedBy`, t.`deleted_at` AS `DeletedAt`, t.`deleted_by` AS `DeletedBy` FROM `sections` t  WHERE t.deleted_at IS NULL) q WHERE (p_college_id IS NULL OR q.`CollegeId`=p_college_id) AND (p_department_id IS NULL OR q.`DepartmentId`=p_department_id) AND (p_course_id IS NULL OR q.`CourseId`=p_course_id) AND (p_branch_id IS NULL OR q.`BranchId`=p_branch_id) AND (p_semester_id IS NULL OR q.`SemesterId`=p_semester_id) AND (p_academic_year_id IS NULL OR q.`AcademicYearId`=p_academic_year_id) AND (p_status IS NULL OR LOWER(CAST(q.Status AS CHAR))=LOWER(p_status)) AND (NULLIF(p_search,'') IS NULL OR CONCAT_WS(' ',q.`SectionCode`,q.`SectionName`) LIKE CONCAT('%',p_search,'%')) LIMIT 100001;
ELSEIF p_screen='course-structures' THEN
SELECT * FROM (SELECT t.`structure_id` AS `StructureId`, t.`course_id` AS `CourseId`, t.`branch_id` AS `BranchId`, t.`year_number` AS `YearNumber`, t.`semester_number` AS `SemesterNumber`, t.`semester_name` AS `SemesterName`, t.`status` AS `Status`, t.`created_at` AS `CreatedAt`, t.`created_by` AS `CreatedBy`, t.`updated_at` AS `UpdatedAt`, t.`updated_by` AS `UpdatedBy`, t.`deleted_at` AS `DeletedAt`, t.`deleted_by` AS `DeletedBy`, c.college_id AS `CollegeId`, c.course_name AS `CourseName` FROM `course_structures` t JOIN courses c ON c.course_id=t.course_id WHERE t.deleted_at IS NULL) q WHERE (p_college_id IS NULL OR q.`CollegeId`=p_college_id) AND (p_course_id IS NULL OR q.`CourseId`=p_course_id) AND (p_branch_id IS NULL OR q.`BranchId`=p_branch_id) AND (p_status IS NULL OR LOWER(CAST(q.Status AS CHAR))=LOWER(p_status)) AND (NULLIF(p_search,'') IS NULL OR CONCAT_WS(' ',q.`SemesterName`,q.`CourseName`) LIKE CONCAT('%',p_search,'%')) LIMIT 100001;
ELSEIF p_screen='students' THEN
SELECT * FROM (SELECT t.`student_id` AS `StudentId`, t.`admission_id` AS `AdmissionId`, t.`college_id` AS `CollegeId`, t.`student_code` AS `StudentCode`, t.`full_name` AS `FullName`, t.`gender` AS `Gender`, t.`date_of_birth` AS `DateOfBirth`, t.`email` AS `Email`, t.`mobile` AS `Mobile`, t.`blood_group` AS `BloodGroup`, t.`address` AS `Address`, t.`course_id` AS `CourseId`, t.`branch_id` AS `BranchId`, t.`academic_year_id` AS `AcademicYearId`, t.`status` AS `Status`, t.`created_at` AS `CreatedAt`, t.`created_by` AS `CreatedBy`, t.`updated_at` AS `UpdatedAt`, t.`updated_by` AS `UpdatedBy`, t.`deleted_at` AS `DeletedAt`, t.`deleted_by` AS `DeletedBy`, c.course_name AS `CourseName`, c.department_id AS `DepartmentId`, b.branch_name AS `BranchName` FROM `students` t LEFT JOIN courses c ON c.course_id=t.course_id LEFT JOIN branches b ON b.branch_id=t.branch_id WHERE t.deleted_at IS NULL) q WHERE (p_college_id IS NULL OR q.`CollegeId`=p_college_id) AND (p_department_id IS NULL OR q.`DepartmentId`=p_department_id) AND (p_course_id IS NULL OR q.`CourseId`=p_course_id) AND (p_branch_id IS NULL OR q.`BranchId`=p_branch_id) AND (p_academic_year_id IS NULL OR q.`AcademicYearId`=p_academic_year_id) AND (p_status IS NULL OR LOWER(CAST(q.Status AS CHAR))=LOWER(p_status)) AND (NULLIF(p_search,'') IS NULL OR CONCAT_WS(' ',q.`StudentCode`,q.`FullName`,q.`Email`,q.`CourseName`,q.`BranchName`) LIKE CONCAT('%',p_search,'%')) LIMIT 100001;
ELSEIF p_screen='student-profiles' THEN
SELECT * FROM (SELECT t.`PermanentCountry` AS `PermanentCountry`, t.`PermanentState` AS `PermanentState`, t.`PermanentDistrict` AS `PermanentDistrict`, t.`PermanentCity` AS `PermanentCity`, t.`PermanentPincode` AS `PermanentPincode`, t.`PermanentAddress` AS `PermanentAddress`, t.`PermanentHouseNumber` AS `PermanentHouseNumber`, t.`HouseNumber` AS `HouseNumber`, t.`StudentProfileId` AS `StudentProfileId`, t.`StudentId` AS `StudentId`, t.`AlternateEmail` AS `AlternateEmail`, t.`AlternateMobile` AS `AlternateMobile`, t.`BloodGroup` AS `BloodGroup`, t.`Nationality` AS `Nationality`, t.`Religion` AS `Religion`, t.`Category` AS `Category`, t.`Address` AS `Address`, t.`City` AS `City`, t.`District` AS `District`, t.`State` AS `State`, t.`Country` AS `Country`, t.`Pincode` AS `Pincode`, t.`ProfileStatus` AS `ProfileStatus`, t.`IsProfileCompleted` AS `IsProfileCompleted`, t.`IsVerified` AS `IsVerified`, t.`VerifiedBy` AS `VerifiedBy`, t.`VerifiedAt` AS `VerifiedAt`, t.`ProfileCompletionPercentage` AS `ProfileCompletionPercentage`, t.`Remarks` AS `Remarks`, t.`IsActive` AS `IsActive`, t.`IsDeleted` AS `IsDeleted`, t.`CreatedBy` AS `CreatedBy`, t.`CreatedAt` AS `CreatedAt`, t.`UpdatedBy` AS `UpdatedBy`, t.`UpdatedAt` AS `UpdatedAt`, t.`DeletedBy` AS `DeletedBy`, t.`DeletedAt` AS `DeletedAt`, s.college_id AS `CollegeId`, s.full_name AS `FullName`, s.course_id AS `CourseId`, s.branch_id AS `BranchId`, s.academic_year_id AS `AcademicYearId` FROM `student_profiles` t JOIN students s ON s.student_id=t.StudentId WHERE t.IsDeleted=0 AND s.deleted_at IS NULL) q WHERE (p_college_id IS NULL OR q.`CollegeId`=p_college_id) AND (p_course_id IS NULL OR q.`CourseId`=p_course_id) AND (p_branch_id IS NULL OR q.`BranchId`=p_branch_id) AND (p_academic_year_id IS NULL OR q.`AcademicYearId`=p_academic_year_id) AND (NULLIF(p_search,'') IS NULL OR CONCAT_WS(' ',q.`AlternateEmail`,q.`FullName`) LIKE CONCAT('%',p_search,'%')) LIMIT 100001;
ELSEIF p_screen='student-admissions' THEN
SELECT * FROM (SELECT `AdmissionId` AS `AdmissionId`, `RegistrationNo` AS `RegistrationNo`, `AdmissionNo` AS `AdmissionNo`, `FirstName` AS `FirstName`, `LastName` AS `LastName`, `Gender` AS `Gender`, `DateOfBirth` AS `DateOfBirth`, `StudentEmail` AS `StudentEmail`, `MobileNumber` AS `MobileNumber`, `AdmissionType` AS `AdmissionType`, `EntryType` AS `EntryType`, `Regulation` AS `Regulation`, `Batch` AS `Batch`, `AdmissionStatus` AS `Status`, `AcademicYearId` AS `AcademicYearId`, `AcademicYearName` AS `AcademicYearName`, `AdmissionCollegeId` AS `CollegeId`, `AdmissionCollegeName` AS `CollegeName`, `AdmissionDepartmentId` AS `DepartmentId`, `AdmissionDepartmentName` AS `DepartmentName`, `AdmissionCourseId` AS `CourseId`, `AdmissionCourseName` AS `CourseName`, `AdmissionBranchId` AS `BranchId`, `AdmissionBranchName` AS `BranchName`, `SemesterId` AS `SemesterId`, `SemesterName` AS `SemesterName`, `SectionId` AS `SectionId`, `SectionName` AS `SectionName`, `IsActive` AS `IsActive`, `CreatedAt` AS `CreatedAt`, `UpdatedAt` AS `UpdatedAt` FROM vw_cms_admission_directory WHERE IsDeleted=0) q WHERE (p_college_id IS NULL OR q.`CollegeId`=p_college_id) AND (p_department_id IS NULL OR q.`DepartmentId`=p_department_id) AND (p_course_id IS NULL OR q.`CourseId`=p_course_id) AND (p_branch_id IS NULL OR q.`BranchId`=p_branch_id) AND (p_semester_id IS NULL OR q.`SemesterId`=p_semester_id) AND (p_academic_year_id IS NULL OR q.`AcademicYearId`=p_academic_year_id) AND (p_status IS NULL OR LOWER(CAST(q.Status AS CHAR))=LOWER(p_status)) AND (NULLIF(p_search,'') IS NULL OR CONCAT_WS(' ',q.`RegistrationNo`,q.`AdmissionNo`,q.`FirstName`,q.`LastName`,q.`StudentEmail`,q.`AcademicYearName`,q.`CollegeName`,q.`DepartmentName`,q.`CourseName`,q.`BranchName`,q.`SemesterName`,q.`SectionName`) LIKE CONCAT('%',p_search,'%')) LIMIT 100001;
ELSEIF p_screen='promotions' THEN
SELECT * FROM (SELECT t.`promotion_id` AS `PromotionId`, t.`student_id` AS `StudentId`, t.`from_academic_year_id` AS `FromAcademicYearId`, t.`to_academic_year_id` AS `ToAcademicYearId`, t.`from_course_id` AS `FromCourseId`, t.`to_course_id` AS `ToCourseId`, t.`from_branch_id` AS `FromBranchId`, t.`to_branch_id` AS `ToBranchId`, t.`from_semester` AS `FromSemester`, t.`to_semester` AS `ToSemester`, t.`promotion_status` AS `PromotionStatus`, t.`decision` AS `Decision`, t.`decision_date` AS `DecisionDate`, t.`decision_by` AS `DecisionBy`, t.`remarks` AS `Remarks`, t.`created_at` AS `CreatedAt`, t.`created_by` AS `CreatedBy`, t.`updated_at` AS `UpdatedAt`, t.`updated_by` AS `UpdatedBy`, t.`deleted_at` AS `DeletedAt`, t.`deleted_by` AS `DeletedBy`, t.`college_id` AS `CollegeId`, t.`from_section_id` AS `FromSectionId`, t.`to_section_id` AS `ToSectionId`, t.`attendance_percentage` AS `AttendancePercentage`, t.`total_marks` AS `TotalMarks`, t.`obtained_marks` AS `ObtainedMarks`, t.`marks_percentage` AS `MarksPercentage`, t.`passed_subjects` AS `PassedSubjects`, t.`failed_subjects` AS `FailedSubjects`, t.`backlog_count` AS `BacklogCount`, t.`promotion_eligibility` AS `PromotionEligibility`, t.`eligibility_remarks` AS `EligibilityRemarks`, t.`promotion_type` AS `PromotionType`, t.`promotion_date` AS `PromotionDate`, t.`effective_date` AS `EffectiveDate`, t.`promotion_reason` AS `PromotionReason`, t.`rejection_reason` AS `RejectionReason`, t.`approved_at` AS `ApprovedAt`, t.`is_final` AS `IsFinal`, t.`promotion_order` AS `PromotionOrder`, t.`is_active` AS `IsActive`, s.full_name AS `StudentName` FROM `student_promotions` t JOIN students s ON s.student_id=t.student_id WHERE t.deleted_at IS NULL) q WHERE (p_college_id IS NULL OR q.`CollegeId`=p_college_id) AND (NULLIF(p_search,'') IS NULL OR CONCAT_WS(' ',q.`StudentName`) LIKE CONCAT('%',p_search,'%')) LIMIT 100001;
ELSEIF p_screen='users' THEN
SELECT * FROM (SELECT t.`user_id` AS `UserId`, t.`college_id` AS `CollegeId`, t.`employee_user_id` AS `EmployeeUserId`, t.`full_name` AS `FullName`, t.`email` AS `Email`, t.`mobile` AS `Mobile`, t.`status` AS `Status`, t.`created_at` AS `CreatedAt`, t.`updated_at` AS `UpdatedAt` FROM `users` t  WHERE t.deleted_at IS NULL) q WHERE (p_college_id IS NULL OR q.`CollegeId`=p_college_id) AND (p_status IS NULL OR LOWER(CAST(q.Status AS CHAR))=LOWER(p_status)) AND (NULLIF(p_search,'') IS NULL OR CONCAT_WS(' ',q.`FullName`,q.`Email`) LIKE CONCAT('%',p_search,'%')) LIMIT 100001;
ELSEIF p_screen='roles' THEN
SELECT * FROM (SELECT t.`role_id` AS `RoleId`, t.`role_name` AS `RoleName`, t.`role_code` AS `RoleCode`, t.`description` AS `Description`, t.`status` AS `Status`, t.`created_at` AS `CreatedAt`, t.`created_by` AS `CreatedBy`, t.`updated_at` AS `UpdatedAt`, t.`updated_by` AS `UpdatedBy`, t.`deleted_at` AS `DeletedAt`, t.`deleted_by` AS `DeletedBy` FROM `roles` t  WHERE t.deleted_at IS NULL) q WHERE (p_status IS NULL OR LOWER(CAST(q.Status AS CHAR))=LOWER(p_status)) AND (NULLIF(p_search,'') IS NULL OR CONCAT_WS(' ',q.`RoleName`,q.`RoleCode`) LIKE CONCAT('%',p_search,'%')) LIMIT 100001;
ELSEIF p_screen='faculty' THEN
SELECT * FROM (SELECT t.`employee_profile_id` AS `EmployeeProfileId`, t.`user_id` AS `UserId`, t.`department_id` AS `DepartmentId`, t.`designation` AS `Designation`, t.`status` AS `Status`, t.`created_at` AS `CreatedAt`, t.`updated_at` AS `UpdatedAt`, u.college_id AS `CollegeId`, u.full_name AS `FullName`, u.employee_user_id AS `EmployeeUserId` FROM `employee_profiles` t JOIN users u ON u.user_id=t.user_id WHERE t.deleted_at IS NULL) q WHERE (p_college_id IS NULL OR q.`CollegeId`=p_college_id) AND (p_department_id IS NULL OR q.`DepartmentId`=p_department_id) AND (p_status IS NULL OR LOWER(CAST(q.Status AS CHAR))=LOWER(p_status)) AND (NULLIF(p_search,'') IS NULL OR CONCAT_WS(' ',q.`FullName`) LIKE CONCAT('%',p_search,'%')) LIMIT 100001;
ELSEIF p_screen='fee-structures' THEN
SELECT * FROM (SELECT t.`fee_master_id` AS `FeeMasterId`, t.`academic_year_id` AS `AcademicYearId`, t.`department_id` AS `DepartmentId`, t.`course_id` AS `CourseId`, t.`branch_id` AS `BranchId`, t.`semester_id` AS `SemesterId`, t.`admission_type` AS `AdmissionType`, t.`quota` AS `Quota`, t.`student_category` AS `StudentCategory`, t.`tuition_fee` AS `TuitionFee`, t.`admission_fee` AS `AdmissionFee`, t.`effective_from` AS `EffectiveFrom`, t.`effective_to` AS `EffectiveTo`, t.`status` AS `Status`, t.`created_at` AS `CreatedAt`, t.`created_by` AS `CreatedBy`, t.`updated_at` AS `UpdatedAt`, t.`updated_by` AS `UpdatedBy`, c.college_id AS `CollegeId` FROM `fee_master_structures` t JOIN courses c ON c.course_id=t.course_id WHERE 1=1) q WHERE (p_college_id IS NULL OR q.`CollegeId`=p_college_id) AND (p_department_id IS NULL OR q.`DepartmentId`=p_department_id) AND (p_course_id IS NULL OR q.`CourseId`=p_course_id) AND (p_branch_id IS NULL OR q.`BranchId`=p_branch_id) AND (p_semester_id IS NULL OR q.`SemesterId`=p_semester_id) AND (p_academic_year_id IS NULL OR q.`AcademicYearId`=p_academic_year_id) AND (p_status IS NULL OR LOWER(CAST(q.Status AS CHAR))=LOWER(p_status)) LIMIT 100001;
ELSEIF p_screen='hostel-fees' THEN
SELECT * FROM (SELECT t.`hostel_fee_master_id` AS `HostelFeeMasterId`, t.`academic_year_id` AS `AcademicYearId`, t.`hostel_type` AS `HostelType`, t.`room_type` AS `RoomType`, t.`amount` AS `Amount`, t.`effective_from` AS `EffectiveFrom`, t.`effective_to` AS `EffectiveTo`, t.`status` AS `Status`, t.`created_at` AS `CreatedAt`, t.`created_by` AS `CreatedBy`, t.`updated_at` AS `UpdatedAt`, t.`updated_by` AS `UpdatedBy` FROM `hostel_fee_master` t  WHERE 1=1) q WHERE (p_academic_year_id IS NULL OR q.`AcademicYearId`=p_academic_year_id) AND (p_status IS NULL OR LOWER(CAST(q.Status AS CHAR))=LOWER(p_status)) LIMIT 100001;
ELSEIF p_screen='transport-fees' THEN
SELECT * FROM (SELECT t.`transport_fee_master_id` AS `TransportFeeMasterId`, t.`academic_year_id` AS `AcademicYearId`, t.`route_id` AS `RouteId`, t.`route_code` AS `RouteCode`, t.`route_name` AS `RouteName`, t.`amount` AS `Amount`, t.`effective_from` AS `EffectiveFrom`, t.`effective_to` AS `EffectiveTo`, t.`status` AS `Status`, t.`created_at` AS `CreatedAt`, t.`created_by` AS `CreatedBy`, t.`updated_at` AS `UpdatedAt`, t.`updated_by` AS `UpdatedBy` FROM `transport_fee_master` t  WHERE 1=1) q WHERE (p_academic_year_id IS NULL OR q.`AcademicYearId`=p_academic_year_id) AND (p_status IS NULL OR LOWER(CAST(q.Status AS CHAR))=LOWER(p_status)) AND (NULLIF(p_search,'') IS NULL OR CONCAT_WS(' ',q.`RouteCode`,q.`RouteName`) LIKE CONCAT('%',p_search,'%')) LIMIT 100001;
ELSE SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Unsupported export screen.'; END IF;
END$$
DELIMITER ;
