USE cms_btech;
DELIMITER $$

DROP PROCEDURE IF EXISTS sp_cms_log_api_activity$$
CREATE PROCEDURE sp_cms_log_api_activity(IN p_correlation VARCHAR(100),IN p_user_id BIGINT,IN p_screen VARCHAR(100),IN p_action VARCHAR(160),IN p_method VARCHAR(10),IN p_route VARCHAR(500),IN p_status INT,IN p_duration BIGINT) BEGIN
INSERT INTO api_activity_logs(correlation_id,user_id,screen,action_name,http_method,route,status_code,duration_ms) VALUES(p_correlation,p_user_id,p_screen,p_action,p_method,p_route,p_status,p_duration);
END$$

DROP PROCEDURE IF EXISTS sp_cms_activity_list$$
CREATE PROCEDURE sp_cms_activity_list(IN p_screen VARCHAR(100),IN p_correlation VARCHAR(100),IN p_limit INT) BEGIN
SELECT log_id AS logId,correlation_id AS correlationId,user_id AS userId,screen,action_name AS actionName,http_method AS method,route,status_code AS statusCode,duration_ms AS durationMs,occurred_at AS occurredAt FROM api_activity_logs WHERE (p_screen IS NULL OR screen=p_screen) AND (p_correlation IS NULL OR correlation_id=p_correlation) ORDER BY log_id DESC LIMIT p_limit;
END$$

DROP PROCEDURE IF EXISTS sp_cms_status_history$$
CREATE PROCEDURE sp_cms_status_history(IN p_entity VARCHAR(40),IN p_id BIGINT) BEGIN
SELECT audit_id AS auditId,entity_type AS entityType,entity_id AS entityId,old_status AS oldStatus,new_status AS newStatus,changed_by AS changedBy,changed_at AS changedAt FROM entity_status_audit WHERE entity_type=p_entity AND entity_id=p_id ORDER BY audit_id DESC;
END$$

DROP PROCEDURE IF EXISTS sp_cms_dependency_impact$$
CREATE PROCEDURE sp_cms_dependency_impact(IN p_entity VARCHAR(40),IN p_id BIGINT) BEGIN
IF p_entity='departments' THEN
SELECT department_id AS id,status,(SELECT COUNT(*) FROM courses WHERE department_id=p_id AND status=1 AND deleted_at IS NULL) AS activeCoursesCount,(SELECT COUNT(*) FROM branches WHERE department_id=p_id AND status=1 AND deleted_at IS NULL) AS activeBranchesCount,(SELECT COUNT(*) FROM sections WHERE department_id=p_id AND status=1 AND deleted_at IS NULL AND is_archived=0) AS activeSectionsCount,(SELECT COUNT(DISTINCT student_id) FROM vw_cms_student_links WHERE department_id=p_id) AS studentCount,(SELECT COUNT(DISTINCT student_id) FROM vw_cms_student_links WHERE department_id=p_id) AS associatedStudentCount,(SELECT COUNT(DISTINCT student_id) FROM vw_cms_student_links WHERE department_id=p_id AND status=1) AS activeStudentCount,(SELECT COUNT(*) FROM vw_cms_admission_directory WHERE AdmissionDepartmentId=p_id AND IsDeleted=0 AND IsActive=1 AND AdmissionStatus NOT IN ('Rejected','Cancelled','Withdrawn')) AS activeAdmissionCount,((SELECT COUNT(*) FROM courses WHERE department_id=p_id AND status=1 AND deleted_at IS NULL)+(SELECT COUNT(*) FROM branches WHERE department_id=p_id AND status=1 AND deleted_at IS NULL)+(SELECT COUNT(*) FROM sections WHERE department_id=p_id AND status=1 AND deleted_at IS NULL AND is_archived=0)+(SELECT COUNT(DISTINCT student_id) FROM vw_cms_student_links WHERE department_id=p_id AND status=1)+(SELECT COUNT(*) FROM vw_cms_admission_directory WHERE AdmissionDepartmentId=p_id AND IsDeleted=0 AND IsActive=1 AND AdmissionStatus NOT IN ('Rejected','Cancelled','Withdrawn')))=0 AS canDeactivate,'No cascade. Active dependencies must be reassigned or deactivated first. Historical records remain available.' AS policy FROM departments WHERE department_id=p_id AND deleted_at IS NULL LIMIT 1;
ELSEIF p_entity='courses' THEN
SELECT course_id AS id,status,(SELECT COUNT(*) FROM branches WHERE course_id=p_id AND status=1 AND deleted_at IS NULL) AS activeBranchesCount,(SELECT COUNT(*) FROM semesters WHERE course_id=p_id AND status=1 AND is_archived=0) AS activeSemestersCount,(SELECT COUNT(*) FROM sections WHERE course_id=p_id AND status=1 AND deleted_at IS NULL AND is_archived=0) AS activeSectionsCount,(SELECT COUNT(DISTINCT student_id) FROM vw_cms_student_links WHERE course_id=p_id) AS studentCount,(SELECT COUNT(DISTINCT student_id) FROM vw_cms_student_links WHERE course_id=p_id) AS associatedStudentCount,(SELECT COUNT(DISTINCT student_id) FROM vw_cms_student_links WHERE course_id=p_id AND status=1) AS activeStudentCount,(SELECT COUNT(*) FROM vw_cms_admission_directory WHERE AdmissionCourseId=p_id AND IsDeleted=0 AND IsActive=1 AND AdmissionStatus NOT IN ('Rejected','Cancelled','Withdrawn')) AS activeAdmissionCount,((SELECT COUNT(*) FROM branches WHERE course_id=p_id AND status=1 AND deleted_at IS NULL)+(SELECT COUNT(*) FROM semesters WHERE course_id=p_id AND status=1 AND is_archived=0)+(SELECT COUNT(*) FROM sections WHERE course_id=p_id AND status=1 AND deleted_at IS NULL AND is_archived=0)+(SELECT COUNT(DISTINCT student_id) FROM vw_cms_student_links WHERE course_id=p_id AND status=1)+(SELECT COUNT(*) FROM vw_cms_admission_directory WHERE AdmissionCourseId=p_id AND IsDeleted=0 AND IsActive=1 AND AdmissionStatus NOT IN ('Rejected','Cancelled','Withdrawn')))=0 AS canDeactivate,'No cascade. Active dependencies must be reassigned or deactivated first. Historical records remain available.' AS policy FROM courses WHERE course_id=p_id AND deleted_at IS NULL LIMIT 1;
ELSEIF p_entity='branches' THEN
SELECT branch_id AS id,status,(SELECT COUNT(*) FROM semesters WHERE branch_id=p_id AND status=1 AND is_archived=0) AS activeSemestersCount,(SELECT COUNT(*) FROM sections WHERE branch_id=p_id AND status=1 AND deleted_at IS NULL AND is_archived=0) AS activeSectionsCount,(SELECT COUNT(DISTINCT student_id) FROM vw_cms_student_links WHERE branch_id=p_id) AS studentCount,(SELECT COUNT(DISTINCT student_id) FROM vw_cms_student_links WHERE branch_id=p_id) AS associatedStudentCount,(SELECT COUNT(DISTINCT student_id) FROM vw_cms_student_links WHERE branch_id=p_id AND status=1) AS activeStudentCount,(SELECT COUNT(*) FROM vw_cms_admission_directory WHERE AdmissionBranchId=p_id AND IsDeleted=0 AND IsActive=1 AND AdmissionStatus NOT IN ('Rejected','Cancelled','Withdrawn')) AS activeAdmissionCount,((SELECT COUNT(*) FROM semesters WHERE branch_id=p_id AND status=1 AND is_archived=0)+(SELECT COUNT(*) FROM sections WHERE branch_id=p_id AND status=1 AND deleted_at IS NULL AND is_archived=0)+(SELECT COUNT(DISTINCT student_id) FROM vw_cms_student_links WHERE branch_id=p_id AND status=1)+(SELECT COUNT(*) FROM vw_cms_admission_directory WHERE AdmissionBranchId=p_id AND IsDeleted=0 AND IsActive=1 AND AdmissionStatus NOT IN ('Rejected','Cancelled','Withdrawn')))=0 AS canDeactivate,'No cascade. Active dependencies must be reassigned or deactivated first. Historical records remain available.' AS policy FROM branches WHERE branch_id=p_id AND deleted_at IS NULL LIMIT 1;
ELSEIF p_entity='semesters' THEN
SELECT semester_id AS id,status,(SELECT COUNT(*) FROM sections WHERE semester_id=p_id AND status=1 AND deleted_at IS NULL AND is_archived=0) AS activeSectionsCount,(SELECT COUNT(DISTINCT student_id) FROM vw_cms_student_links WHERE semester_id=p_id) AS studentCount,(SELECT COUNT(DISTINCT student_id) FROM vw_cms_student_links WHERE semester_id=p_id) AS associatedStudentCount,(SELECT COUNT(DISTINCT student_id) FROM vw_cms_student_links WHERE semester_id=p_id AND status=1) AS activeStudentCount,(SELECT COUNT(*) FROM vw_cms_admission_directory WHERE SemesterId=p_id AND IsDeleted=0 AND IsActive=1 AND AdmissionStatus NOT IN ('Rejected','Cancelled','Withdrawn')) AS activeAdmissionCount,((SELECT COUNT(*) FROM sections WHERE semester_id=p_id AND status=1 AND deleted_at IS NULL AND is_archived=0)+(SELECT COUNT(DISTINCT student_id) FROM vw_cms_student_links WHERE semester_id=p_id AND status=1)+(SELECT COUNT(*) FROM vw_cms_admission_directory WHERE SemesterId=p_id AND IsDeleted=0 AND IsActive=1 AND AdmissionStatus NOT IN ('Rejected','Cancelled','Withdrawn')))=0 AS canDeactivate,'No cascade. Active dependencies must be reassigned or deactivated first. Historical records remain available.' AS policy FROM semesters WHERE semester_id=p_id AND is_archived=0 LIMIT 1;
ELSEIF p_entity='sections' THEN
SELECT section_id AS id,status,(SELECT COUNT(DISTINCT student_id) FROM vw_cms_student_links WHERE section_id=p_id) AS studentCount,(SELECT COUNT(DISTINCT student_id) FROM vw_cms_student_links WHERE section_id=p_id) AS associatedStudentCount,(SELECT COUNT(DISTINCT student_id) FROM vw_cms_student_links WHERE section_id=p_id AND status=1) AS activeStudentCount,(SELECT COUNT(*) FROM vw_cms_admission_directory WHERE SectionId=p_id AND IsDeleted=0 AND IsActive=1 AND AdmissionStatus NOT IN ('Rejected','Cancelled','Withdrawn')) AS activeAdmissionCount,((SELECT COUNT(DISTINCT student_id) FROM vw_cms_student_links WHERE section_id=p_id AND status=1)+(SELECT COUNT(*) FROM vw_cms_admission_directory WHERE SectionId=p_id AND IsDeleted=0 AND IsActive=1 AND AdmissionStatus NOT IN ('Rejected','Cancelled','Withdrawn')))=0 AS canDeactivate,'No cascade. Active dependencies must be reassigned or deactivated first. Historical records remain available.' AS policy FROM sections WHERE section_id=p_id AND deleted_at IS NULL LIMIT 1;
ELSEIF p_entity='students' THEN
SELECT student_id AS id,status,0 AS studentCount,0 AS associatedStudentCount,0 AS activeStudentCount,0 AS activeAdmissionCount,(0)=0 AS canDeactivate,'No cascade. Active dependencies must be reassigned or deactivated first. Historical records remain available.' AS policy FROM students WHERE student_id=p_id AND deleted_at IS NULL LIMIT 1;
ELSE SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Unsupported dependency entity.'; END IF;
END$$

DELIMITER ;