import { cloneElement, useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { FiAlertCircle, FiArrowLeft, FiEdit2, FiEye, FiFilter, FiGitBranch, FiPlus, FiSearch } from 'react-icons/fi'
import DashboardLayout from '../../layouts/DashboardLayout'
import { branchApi } from '../../api/apiEndpoints'
import { getBranches, saveBranch } from './Course'
import { getCourses, getDepartments } from '../../auth/collegeApi'
import './Branch.css'

const blank={departmentId:'',courseId:'',name:'',code:'',shortName:'',branchType:'Core',intakeCapacity:'',description:'',status:'Active'}
const isBtech=c=>c.type==='Undergraduate'&&/b\.?tech|bachelor\s+of\s+technology/i.test(`${c.code||''} ${c.name||''} ${c.shortName||''}`)
const listFrom=response=>{const data=response?.data??response;return Array.isArray(data)?data:Array.isArray(data?.items)?data.items:Array.isArray(data?.data)?data.data:[]}
const mapDepartment=record=>({id:record.id??record.departmentId,name:record.departmentName??record.name??''})
const mapCourse=record=>({id:record.id??record.courseId,name:record.courseName??record.name??'',code:record.courseCode??record.code??'',shortName:record.courseShortName??record.shortName??'',type:record.courseType??record.type??'Undergraduate',departmentId:record.departmentId??''})
const normalize=b=>({...b,id:b.branchId??b.id,name:b.branchName??b.name??'',code:b.branchCode??b.code??'',status:Number(b.status)===0||b.status==='Inactive'?'Inactive':'Active',duration:b.duration??4,totalSemesters:b.totalSemesters??b.semesters??8})
const intake=b=>Number(b.intakeCapacity??b.intake??0), type=b=>b.branchType||(b.specialization?'Specialization':'Core')
const Page=({children})=><DashboardLayout><main className="cm-page branch-management">{children}</main></DashboardLayout>
const Header=({title,text,children})=><header className="cm-header"><div><h1>{title}</h1><p>{text}</p></div><div className="cm-row-actions">{children}</div></header>
const Badge=({value,kind='status'})=><span className={`branch-badge ${kind} ${String(value).toLowerCase()}`}>{kind==='status'&&<i/>}{value}</span>
const Notice=({children})=>children?<p className={String(children).startsWith('Branch ') ? 'branch-api-success' : 'branch-api-error'} role={String(children).startsWith('Branch ') ? 'status' : 'alert'}><FiAlertCircle/>{children}</p>:null
const fieldPlaceholders={'Branch Name *':'Enter branch name','Branch Code *':'Enter branch code, e.g. CSE','Short Name':'Enter short name','Description':'Enter branch description','Approved Intake *':'Enter intake capacity'}
const Field=({label,error,wide,children})=><label className={`cm-field ${wide?'wide':''}`}><span>{label}</span>{cloneElement(children,{placeholder:children.props.placeholder||fieldPlaceholders[label]})}{error&&<small className="cm-error">{error}</small>}</label>
const codeFor=name=>name.split(/\s+/).filter(Boolean).filter(w=>!['and','&','of','the'].includes(w.toLowerCase())).map(w=>w[0]).join('').slice(0,8).toUpperCase()

function List(){
 const [params]=useSearchParams(),[departments,setDepartments]=useState([]),[courses,setCourses]=useState([]),[branches,setBranches]=useState(()=>getBranches().map(normalize)),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const [filters,setFilters]=useState({query:'',departmentId:'',courseId:params.get('course')||'',branchType:'',status:''})
 const load=async(courseId='')=>{setLoading(true);try{const [branchRows,departmentResponse,courseResponse]=await Promise.all([courseId?branchApi.getByCourse(courseId):branchApi.getAll(),getDepartments(),getCourses()]);setBranches(branchRows.map(normalize));setDepartments(listFrom(departmentResponse.data).map(mapDepartment));setCourses(listFrom(courseResponse.data).map(mapCourse).filter(isBtech));setError('')}catch(e){setError(e.message||'Unable to load branch data.')}finally{setLoading(false)}}
 useEffect(()=>{load(filters.courseId)},[filters.courseId])
 const dep=id=>departments.find(x=>String(x.id)===String(id))?.name||branches.find(x=>String(x.departmentId)===String(id))?.departmentName||'Not available',course=id=>courses.find(x=>String(x.id)===String(id))?.shortName||branches.find(x=>String(x.courseId)===String(id))?.courseName||'Not available'
 const rows=useMemo(()=>branches.filter(b=>`${b.name} ${b.code} ${b.departmentName||dep(b.departmentId)} ${b.courseName||course(b.courseId)}`.toLowerCase().includes(filters.query.toLowerCase())&&(!filters.departmentId||String(b.departmentId)===filters.departmentId)&&(!filters.courseId||String(b.courseId)===filters.courseId)&&(!filters.branchType||type(b)===filters.branchType)&&(!filters.status||b.status===filters.status)),[branches,filters])
 const stats=[['Total Branches',branches.length],['Active Branches',branches.filter(x=>x.status==='Active').length],['Inactive Branches',branches.filter(x=>x.status==='Inactive').length],['Core Branches',branches.filter(x=>type(x)==='Core').length],['Specializations',branches.filter(x=>type(x)==='Specialization').length],['Total Approved Intake',branches.reduce((n,x)=>n+intake(x),0).toLocaleString('en-IN')]]
 const set=(key,value)=>setFilters(current=>key==='departmentId'?{...current,departmentId:value,courseId:''}:{...current,[key]:value})
 const toggle=async b=>{const status=b.status==='Active'?'Inactive':'Active';if(!window.confirm(`Are you sure you want to ${status==='Inactive'?'deactivate':'activate'} ${b.code}?`))return;setError('');try{const saved=normalize(await branchApi.update(b.id,{...b,status}));saveBranch(saved);setBranches(rows=>rows.map(x=>x.id===b.id?saved:x));setError(`Branch ${status==='Inactive'?'deactivated':'activated'} successfully.`)}catch(e){setError(e.message||'Unable to update branch status.')}}
 const has=Object.values(filters).some(Boolean),courseOptions=courses.filter(c=>!filters.departmentId||String(c.departmentId)===filters.departmentId)
 return <Page><Header title="B.Tech Branch Management" text="Manage B.Tech undergraduate branches and specializations."><Link className="cm-button" to="/branches/add"><FiPlus/> Add Branch</Link></Header><section className="branch-summary">{stats.map(([a,b])=><article key={a}><span>{a}</span><strong>{b}</strong></article>)}</section><Notice>{error}</Notice><section className="cm-panel branch-filter-toolbar"><label className="branch-search"><FiSearch/><input value={filters.query} onChange={e=>set('query',e.target.value)} placeholder="Search branch name, code or department"/></label><select value={filters.departmentId} onChange={e=>set('departmentId',e.target.value)}><option value="">All Departments</option>{departments.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={filters.courseId} onChange={e=>set('courseId',e.target.value)}><option value="">All B.Tech Courses</option>{courseOptions.map(x=><option key={x.id} value={x.id}>{x.shortName||x.name}</option>)}</select><select value={filters.branchType} onChange={e=>set('branchType',e.target.value)}><option value="">All Types</option><option>Core</option><option>Specialization</option></select><select value={filters.status} onChange={e=>set('status',e.target.value)}><option value="">All Status</option><option>Active</option><option>Inactive</option></select>{has&&<button className="branch-clear" onClick={()=>setFilters({query:'',departmentId:'',courseId:'',branchType:'',status:''})}><FiFilter/> Clear Filters</button>}</section><section className="cm-panel branch-directory"><div className="branch-results">{loading?'Loading branches…':<>Showing <strong>{rows.length}</strong> of <strong>{branches.length}</strong> branches</>}</div>{rows.length?<div className="branch-table-scroll"><table className="branch-table"><thead><tr>{['Branch','Code','Department','Course','Type','Duration','Intake','Status','Actions'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(b=><tr key={b.id}><td><strong>{b.name}</strong><small>{b.code}</small></td><td><b>{b.code}</b></td><td>{b.departmentName||dep(b.departmentId)}</td><td>{b.courseName||course(b.courseId)}</td><td><Badge value={type(b)} kind="type"/></td><td>{b.duration} Years<small>{b.totalSemesters} Semesters</small></td><td>{intake(b)}</td><td><Badge value={b.status}/></td><td><div className="branch-actions"><Link to={`/branches/${b.id}`}><FiEye/></Link><Link to={`/branches/${b.id}/edit`}><FiEdit2/></Link><button onClick={()=>toggle(b)}>{b.status==='Active'?'Deactivate':'Activate'}</button></div></td></tr>)}</tbody></table></div>:!loading&&<div className="branch-empty"><FiGitBranch/><strong>No branches match your filters.</strong></div>}</section></Page>
}

const validate=(v,rows,id,courses)=>{const e={},code=v.code.trim().toUpperCase();if(!v.name.trim())e.name='Branch name is required.';if(!code)e.code='Branch code is required.';else if(!/^[A-Z0-9]+(?:-[A-Z0-9]+)*$/.test(code))e.code='Use uppercase letters, numbers and single hyphens only.';else if(rows.some(x=>String(x.id)!==String(id)&&String(x.code).toUpperCase()===code))e.code='Branch code already exists.';if(!v.departmentId)e.departmentId='Department is required.';if(!v.courseId)e.courseId='Course is required.';if(!Number.isInteger(Number(v.intakeCapacity))||Number(v.intakeCapacity)<1)e.intakeCapacity='Approved intake must be a positive whole number.';const c=courses.find(x=>String(x.id)===String(v.courseId));if(c&&String(c.departmentId)!==String(v.departmentId))e.departmentId='The selected department does not match this course.';return e}
function Form(){
 const {id}=useParams(),[params]=useSearchParams(),navigate=useNavigate(),[departments,setDepartments]=useState([]),[courses,setCourses]=useState([]),[branches,setBranches]=useState([]),[value,setValue]=useState(blank),[errors,setErrors]=useState({}),[step,setStep]=useState(0),[saving,setSaving]=useState(false),[error,setError]=useState(''),[edited,setEdited]=useState(Boolean(id))
 const selectedCourseId=params.get('course')
 useEffect(()=>{let alive=true;Promise.all([getDepartments(),getCourses()]).then(([departmentResponse,courseResponse])=>{if(!alive)return;setDepartments(listFrom(departmentResponse.data).map(mapDepartment));setCourses(listFrom(courseResponse.data).map(mapCourse).filter(isBtech));setError('')}).catch(e=>alive&&setError(e.message||'Unable to load courses and departments.'));return()=>{alive=false}},[])
 useEffect(()=>{let alive=true;Promise.all([branchApi.getAll(),id?branchApi.getById(id):Promise.resolve(null)]).then(([all,current])=>{if(!alive)return;setBranches(all.map(normalize));const selected=courses.find(c=>String(c.id)===selectedCourseId);setValue({...blank,...(current?normalize(current):{}),courseId:current?.courseId||selected?.id||'',departmentId:current?.departmentId||selected?.departmentId||'',intakeCapacity:current?.intakeCapacity??''})}).catch(e=>alive&&setError(e.message||'Unable to load branch data.'));return()=>{alive=false}},[id,courses,selectedCourseId])
 const update=(key,next)=>{setValue(v=>{const n={...v,[key]:next};if(key==='departmentId')n.courseId='';if(key==='courseId')n.departmentId=courses.find(c=>String(c.id)===String(next))?.departmentId||n.departmentId;if(key==='name'&&!edited)n.code=codeFor(next);if(key==='code'){n.code=next.toUpperCase().replace(/\s/g,'');setEdited(true)}return n});setErrors(e=>({...e,[key]:''}))}
 const submit=async()=>{const e=validate(value,branches,id,courses);setErrors(e);if(Object.keys(e).length)return;setSaving(true);setError('');try{const result=normalize(id?await branchApi.update(id,value):await branchApi.create(value));saveBranch(result);navigate(`/branches/${result.id}`)}catch(err){setError(err.message||'Unable to save branch.')}finally{setSaving(false)}}
 const options=courses.filter(c=>!value.departmentId||String(c.departmentId)===String(value.departmentId)),steps=['Branch Identity','Academic Mapping','Structure, Capacity & Status']
 return <Page><Header title={id?'Edit B.Tech Branch':'Add B.Tech Branch'} text="Create a B.Tech undergraduate branch with its academic mapping."><Link className="cm-button secondary" to={id?`/branches/${id}`:'/branches'}><FiArrowLeft/> Cancel</Link></Header><Notice>{error}</Notice><div className="branch-form-layout"><section className="cm-panel branch-form"><nav className="branch-steps">{steps.map((x,i)=><button type="button" key={x} className={step===i?'active':''} onClick={()=>setStep(i)}><b>{i+1}</b>{x}</button>)}</nav>{step===0&&<section><h2>Branch Identity</h2><div className="cm-form-grid"><Field label="Branch Name *" error={errors.name}><input value={value.name} onChange={e=>update('name',e.target.value)}/></Field><Field label="Branch Code *" error={errors.code}><input value={value.code} onChange={e=>update('code',e.target.value)}/></Field><Field label="Short Name"><input value={value.shortName||''} onChange={e=>update('shortName',e.target.value)}/></Field><Field label="Description" wide><textarea value={value.description||''} onChange={e=>update('description',e.target.value)}/></Field></div></section>}{step===1&&<section><h2>Academic Mapping</h2><div className="cm-form-grid"><Field label="Department *" error={errors.departmentId}><select value={value.departmentId} onChange={e=>update('departmentId',e.target.value)}><option value="">Select department</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></Field><Field label="B.Tech Course *" error={errors.courseId}><select value={value.courseId} disabled={!value.departmentId} onChange={e=>update('courseId',e.target.value)}><option value="">Select B.Tech course</option>{options.map(c=><option key={c.id} value={c.id}>{c.shortName||c.name}</option>)}</select></Field></div></section>}{step===2&&<section><h2>Academic Structure, Capacity & Status</h2><div className="cm-form-grid"><Field label="Branch Type"><select value={value.branchType} onChange={e=>update('branchType',e.target.value)}><option>Core</option><option>Specialization</option></select></Field><Field label="Duration"><input value="4 Years" readOnly/></Field><Field label="Total Semesters"><input value="8" readOnly/></Field><Field label="Approved Intake *" error={errors.intakeCapacity}><input type="number" min="1" value={value.intakeCapacity} onChange={e=>update('intakeCapacity',e.target.value)}/></Field><Field label="Status"><select value={value.status} onChange={e=>update('status',e.target.value)}><option>Active</option><option>Inactive</option></select></Field></div></section>}<footer className="branch-form-footer"><button type="button" className="cm-button secondary" disabled={!step} onClick={()=>setStep(s=>s-1)}>Back</button>{step<2?<button type="button" className="cm-button" onClick={()=>setStep(s=>s+1)}>Continue</button>:<button type="button" className="cm-button" disabled={saving} onClick={submit}>{saving?'Saving…':id?'Save Changes':'Create Branch'}</button>}</footer></section></div></Page>
}
function Details(){const{id}=useParams(),[branch,setBranch]=useState(null),[error,setError]=useState('');useEffect(()=>{branchApi.getById(id).then(x=>setBranch(normalize(x))).catch(e=>setError(e.message||'Unable to load branch details.'))},[id]);if(error)return <Page><Notice>{error}</Notice></Page>;if(!branch)return <Page><div className="branch-empty">Loading branch details…</div></Page>;const fields=[['Course',branch.courseName||branch.courseId],['Department',branch.departmentName||branch.departmentId],['Branch Type',type(branch)],['Duration',`${branch.duration} Years`],['Semesters',branch.totalSemesters],['Approved Intake',intake(branch)],['Description',branch.description||'Not available']];return <Page><Header title="B.Tech Branch Details" text="Academic information for this engineering branch."><Link className="cm-button secondary" to="/branches"><FiArrowLeft/> Back</Link><Link className="cm-button" to={`/branches/${id}/edit`}><FiEdit2/> Edit Branch</Link></Header><section className="branch-detail-hero"><div><span className="cm-eyebrow">B.Tech Branch</span><h2>{branch.name}</h2><Badge value={branch.status}/></div><strong>{branch.code}</strong></section><section className="cm-panel branch-detail-grid">{fields.map(([k,v])=><div className="cm-detail" key={k}><span>{k}</span><strong>{v}</strong></div>)}</section></Page>}
export default function Branch({mode='list'}){return mode==='form'?<Form/>:mode==='details'?<Details/>:<List/>}
