import { useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { ArrowLeft, Eye, Network, Pencil, Save } from 'lucide-react'
import DashboardLayout from '../../layouts/DashboardLayout'
import { getBranches, getCourses, getDepartments, saveBranch } from './Course'
import './Branch.css'

const blank = { departmentId: '', courseId: '', code: '', name: '', shortName: '', durationValue: 4, durationUnit: 'Years', semesters: 8, intake: 60, description: '', status: 'Active' }
const Page = ({ children }) => <DashboardLayout><div className="cm-page">{children}</div></DashboardLayout>
const Header = ({ title, text, children }) => <header className="cm-header"><div><span className="cm-eyebrow">Academic Management</span><h1>{title}</h1><p>{text}</p></div><div className="cm-row-actions">{children}</div></header>
const Field = ({ label, error, wide, children }) => <label className={`cm-field ${wide ? 'wide' : ''}`}>{label}{children}{error && <span className="cm-error">{error}</span>}</label>
const ActionIcon = ({ label }) => { const Icon = label.includes('View') ? Eye : label.includes('Edit') ? Pencil : label.includes('Structure') ? Network : label.includes('Back') || label === 'Cancel' ? ArrowLeft : Save; return <Icon aria-hidden="true" /> }
const Button = ({ to, children, ...props }) => to ? <Link className="cm-button secondary" to={to}><ActionIcon label={String(children)} />{children}</Link> : <button type="button" className="cm-button" {...props}><ActionIcon label={String(children)} />{children}</button>

function BranchList() {
  const [params] = useSearchParams(), [branches, setBranches] = useState(getBranches), [departments] = useState(getDepartments), [courses] = useState(getCourses)
  const initialCourse = params.get('course') || ''
  const initialDepartment = courses.find((item) => item.id === initialCourse)?.departmentId || ''
  const [filters, setFilters] = useState({ query: '', departmentId: String(initialDepartment), courseId: initialCourse, status: '' })
  const courseOptions = courses.filter((item) => !filters.departmentId || String(item.departmentId) === filters.departmentId)
  const departmentName = (id) => departments.find((item) => String(item.id) === String(id))?.name || 'Not assigned'
  const courseName = (id) => courses.find((item) => item.id === id)?.shortName || courses.find((item) => item.id === id)?.name || 'Not assigned'
  const rows = branches.filter((branch) => `${branch.code} ${branch.name} ${courseName(branch.courseId)} ${departmentName(branch.departmentId)}`.toLowerCase().includes(filters.query.trim().toLowerCase()) && (!filters.departmentId || String(branch.departmentId) === filters.departmentId) && (!filters.courseId || branch.courseId === filters.courseId) && (!filters.status || branch.status === filters.status))
  const changeDepartment = (value) => setFilters({ ...filters, departmentId: value, courseId: '' })
  const toggle = (branch) => { const nextStatus = branch.status === 'Active' ? 'Inactive' : 'Active'; if (!confirm(`${nextStatus === 'Active' ? 'Activate' : 'Deactivate'} ${branch.name}?`)) return; saveBranch({ ...branch, status: nextStatus }); setBranches(getBranches()) }
  return <Page><Header title="Branches" text="Manage engineering disciplines and their programme relationships."><Link className="cm-button" to="/branches/add">+ Add Branch</Link></Header><section className="cm-panel cm-filters branch-filters"><Field label="Search"><input value={filters.query} onChange={(event) => setFilters({ ...filters, query: event.target.value })} placeholder="Search branches..." /></Field><Field label="Department"><select value={filters.departmentId} onChange={(event) => changeDepartment(event.target.value)}><option value="">All Departments</option>{departments.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></Field><Field label="Course"><select value={filters.courseId} onChange={(event) => setFilters({ ...filters, courseId: event.target.value })}><option value="">All Courses</option>{courseOptions.map((item) => <option value={item.id} key={item.id}>{item.shortName || item.name}</option>)}</select></Field><Field label="Status"><select value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value })}><option value="">All Status</option><option>Active</option><option>Inactive</option></select></Field></section><section className="cm-panel cm-table-wrap branch-table-wrap"><table className="cm-table branch-table"><thead><tr>{['#', 'Branch Code', 'Branch Name', 'Course', 'Department', 'Duration', 'Intake', 'Status', 'Actions'].map((item) => <th key={item}>{item}</th>)}</tr></thead><tbody>{rows.map((branch, index) => <tr key={branch.id}><td>{index + 1}</td><td><strong>{branch.code}</strong></td><td>{branch.name}</td><td>{courseName(branch.courseId)}</td><td>{departmentName(branch.departmentId)}</td><td>{branch.durationValue} {branch.durationUnit}</td><td>{branch.intake}</td><td><button className={`cm-status ${branch.status.toLowerCase()}`} onClick={() => toggle(branch)}>{branch.status}</button></td><td><div className="cm-row-actions"><Button to={`/branches/${branch.id}`}>View</Button><Button to={`/branches/${branch.id}/edit`}>Edit</Button><Button to={`/courses/${branch.courseId}/branches/${branch.id}/structure`}>Structure</Button></div></td></tr>)}</tbody></table>{!rows.length && <div className="cm-empty">No branches found. Branches created under a programme will appear here.</div>}</section></Page>
}

function BranchForm() {
  const { id } = useParams(), [params] = useSearchParams(), navigate = useNavigate(), [departments] = useState(getDepartments), [courses] = useState(getCourses), [branches] = useState(getBranches)
  const existing = branches.find((item) => item.id === id), queryCourse = courses.find((item) => item.id === params.get('course'))
  const [value, setValue] = useState(() => existing ? { ...blank, ...existing } : { ...blank, courseId: queryCourse?.id || '', departmentId: queryCourse?.departmentId || '' }), [errors, setErrors] = useState({})
  const activeDepartments = departments.filter((item) => item.status === 'Active' || String(item.id) === String(value.departmentId))
  const courseOptions = courses.filter((item) => String(item.departmentId) === String(value.departmentId) && (item.status === 'Active' || item.id === value.courseId))
  const update = (event) => { const { name, value: nextValue } = event.target; if (name === 'departmentId') setValue({ ...value, departmentId: nextValue, courseId: '' }); else if (name === 'courseId') { const course = courses.find((item) => item.id === nextValue); setValue({ ...value, courseId: nextValue, durationValue: course?.durationValue || value.durationValue, durationUnit: course?.durationUnit || value.durationUnit, semesters: course?.semesters || value.semesters }) } else setValue({ ...value, [name]: name === 'code' ? nextValue.toUpperCase() : nextValue }); if (errors[name]) setErrors({ ...errors, [name]: '' }) }
  const submit = () => { const next = {}, code = value.code.trim().toUpperCase(); if (!value.departmentId) next.departmentId = 'Department is required.'; if (!value.courseId) next.courseId = 'Course is required.'; if (!value.name.trim()) next.name = 'Branch name is required.'; if (!code) next.code = 'Branch code is required.'; else if (branches.some((item) => item.id !== id && item.courseId === value.courseId && item.code.toLowerCase() === code.toLowerCase())) next.code = 'This branch code already exists for the selected course.'; if (!Number.isFinite(Number(value.intake)) || Number(value.intake) < 1) next.intake = 'Intake must be a positive number.'; setErrors(next); if (Object.keys(next).length) return; saveBranch({ ...value, code, name: value.name.trim(), durationValue: Number(value.durationValue), semesters: Number(value.semesters), intake: Number(value.intake) }); navigate('/branches') }
  return <Page><Header title={id ? 'Edit Branch' : 'Add Branch'} text="Create an engineering branch and connect it to its department and programme." /><section className="cm-panel"><div className="cm-form-section"><span className="cm-eyebrow">Academic Mapping</span><div className="cm-form-grid"><Field label="Department *" error={errors.departmentId}><select name="departmentId" autoFocus value={value.departmentId} onChange={update}><option value="">Select department</option>{activeDepartments.map((item) => <option value={item.id} key={item.id}>{item.code} — {item.name}</option>)}</select></Field><Field label="Course / Programme *" error={errors.courseId}><select name="courseId" disabled={!value.departmentId} value={value.courseId} onChange={update}><option value="">{!value.departmentId ? 'Select department first' : courseOptions.length ? 'Select course' : 'No courses available for this department'}</option>{courseOptions.map((item) => <option value={item.id} key={item.id}>{item.shortName || item.name}</option>)}</select></Field></div></div><div className="cm-form-section"><span className="cm-eyebrow">Branch Information</span><div className="cm-form-grid">{[['name', 'Branch Name *'], ['code', 'Branch Code *'], ['shortName', 'Short Name']].map(([name, label]) => <Field label={label} error={errors[name]} key={name}><input name={name} value={value[name]} onChange={update} /></Field>)}<Field label="Duration"><input name="durationValue" type="number" min="1" value={value.durationValue} onChange={update} /></Field><Field label="Total Semesters"><input name="semesters" type="number" min="1" value={value.semesters} onChange={update} /></Field><Field label="Intake Capacity *" error={errors.intake}><input name="intake" type="number" min="1" value={value.intake} onChange={update} /></Field><Field label="Status"><select name="status" value={value.status} onChange={update}><option>Active</option><option>Inactive</option></select></Field><Field label="Description" wide><textarea name="description" value={value.description} onChange={update} /></Field></div></div><div className="cm-actions"><Button to="/branches">Cancel</Button><Button onClick={submit}>{id ? 'Update Branch' : 'Create Branch'}</Button></div></section></Page>
}

function BranchDetails() {
  const { id } = useParams(), [branch] = useState(() => getBranches().find((item) => item.id === id)), [departments] = useState(getDepartments), [courses] = useState(getCourses)
  if (!branch) return <Page><div className="cm-empty">Branch not found.</div></Page>
  const department = departments.find((item) => String(item.id) === String(branch.departmentId)), course = courses.find((item) => item.id === branch.courseId)
  const details = [['Department', department?.name], ['Programme', course?.shortName || course?.name], ['Duration', `${branch.durationValue} ${branch.durationUnit}`], ['Total Semesters', branch.semesters], ['Intake', branch.intake], ['Status', branch.status]]
  return <Page><Header title={branch.name} text={`${department?.name || 'Department'} / ${course?.shortName || course?.name || 'Programme'} / ${branch.code}`}><Button to="/branches">Back</Button><Button to={`/branches/${id}/edit`}>Edit Branch</Button><Button to={`/courses/${branch.courseId}/branches/${id}/structure`}>Academic Structure</Button></Header><section className="cm-panel cm-details">{details.map(([label, value]) => <div className="cm-detail" key={label}><span>{label}</span><strong>{value || 'Not assigned'}</strong></div>)}</section><section className="cm-panel"><h2>Overview</h2><p>{branch.description || 'No description added.'}</p></section></Page>
}

export default function Branch({ mode = 'list' }) { return mode === 'form' ? <BranchForm /> : mode === 'details' ? <BranchDetails /> : <BranchList /> }
