// Sample placement data for B.Tech Institutional Training & Placement Cell

export const defaultDrives = [
  {
    id: 'DRV-101',
    title: 'Microsoft Campus Hiring 2026-27',
    company: 'Microsoft India',
    tier: 'Super Dream',
    role: 'Software Engineer - Cloud & AI',
    ctc: '₹ 44.0 LPA',
    ctcNum: 44.0,
    driveDate: '2026-10-25',
    deadline: '2026-10-20',
    venue: 'Virtual Assessment & Campus Auditorium',
    eligibility: 'B.Tech CSE, IT, ECE · Min 8.0 CGPA · No active backlogs',
    rounds: 'Online Coding Test, Tech Round 1, Tech Round 2, AA/HR Round',
    status: 'Upcoming',
    eligibleBranches: ['CSE', 'IT', 'ECE'],
    applicantsCount: 148,
    shortlistedCount: 32,
    selectedCount: 8,
    minCgpa: 8.0,
    description: 'Microsoft campus hiring for university graduates. Roles in Azure Infrastructure, Microsoft 365, and Applied AI core teams.',
  },
  {
    id: 'DRV-102',
    title: 'Google University Graduate SWE',
    company: 'Google',
    tier: 'Super Dream',
    role: 'Software Development Engineer',
    ctc: '₹ 42.0 LPA',
    ctcNum: 42.0,
    driveDate: '2026-11-04',
    deadline: '2026-10-28',
    venue: 'Google Meet & Hyderabad Campus',
    eligibility: 'B.Tech All Branches · Min 8.5 CGPA · Strong DSA proficiency',
    rounds: 'Online Assessment, Technical Interview 1, Technical Interview 2, Googliness & Leadership',
    status: 'Upcoming',
    eligibleBranches: ['CSE', 'IT', 'ECE', 'EEE'],
    applicantsCount: 210,
    shortlistedCount: 45,
    selectedCount: 6,
    minCgpa: 8.5,
    description: 'Full-time graduate engineering positions across Google Cloud, Search, and Android Core operating system teams.',
  },
  {
    id: 'DRV-103',
    title: 'TCS Digital & Prime National Drive',
    company: 'Tata Consultancy Services',
    tier: 'Dream',
    role: 'Digital Engineer / Full Stack Developer',
    ctc: '₹ 7.5 LPA',
    ctcNum: 7.5,
    driveDate: '2026-10-14',
    deadline: '2026-10-11',
    venue: 'TCS iON Center & Main Seminar Hall',
    eligibility: 'B.Tech All Branches · Min 6.5 CGPA · Max 1 active backlog permitted',
    rounds: 'TCS NQT Advanced, Technical Interview, HR & Managerial',
    status: 'Active',
    eligibleBranches: ['CSE', 'IT', 'ECE', 'MECH', 'CIVIL'],
    applicantsCount: 340,
    shortlistedCount: 110,
    selectedCount: 42,
    minCgpa: 6.5,
    description: 'High-volume national hiring drive for digital and cloud transformation projects across banking, automotive, and retail domains.',
  },
  {
    id: 'DRV-104',
    title: 'Qualcomm Hardware & Firmware Engineering',
    company: 'Qualcomm',
    tier: 'Super Dream',
    role: 'Firmware & Embedded Systems Engineer',
    ctc: '₹ 24.5 LPA',
    ctcNum: 24.5,
    driveDate: '2026-10-18',
    deadline: '2026-10-15',
    venue: 'Placement Cell Lab 2 & Hyderabad Office',
    eligibility: 'B.Tech ECE, CSE, EEE · Min 7.5 CGPA · VLSI/C proficiency',
    rounds: 'Domain Test (C/Verilog), Technical Round 1, System Architecture, HR',
    status: 'Active',
    eligibleBranches: ['ECE', 'CSE', 'EEE'],
    applicantsCount: 95,
    shortlistedCount: 28,
    selectedCount: 10,
    minCgpa: 7.5,
    description: 'Snapdragon SoC design, 5G modem firmware development, and Linux kernel device driver software.',
  },
  {
    id: 'DRV-105',
    title: 'Amazon SDE-1 University Graduate',
    company: 'Amazon',
    tier: 'Super Dream',
    role: 'Software Development Engineer - 1',
    ctc: '₹ 32.0 LPA',
    ctcNum: 32.0,
    driveDate: '2026-09-28',
    deadline: '2026-09-22',
    venue: 'Amazon Chime & Virtual Platform',
    eligibility: 'B.Tech CSE, IT, ECE · Min 7.5 CGPA · 0 backlogs',
    rounds: 'Amazon OA (DSA + Work Style), 3 Rounds of Technical Video Interviews',
    status: 'Completed',
    eligibleBranches: ['CSE', 'IT', 'ECE'],
    applicantsCount: 180,
    shortlistedCount: 42,
    selectedCount: 12,
    minCgpa: 7.5,
    description: 'Hiring for AWS Distributed Computing, Prime Video infrastructure, and Retail e-commerce checkout backend.',
  },
  {
    id: 'DRV-106',
    title: 'L&T Technology Core Graduate Engineer',
    company: 'L&T Technology Services',
    tier: 'Core',
    role: 'Graduate Engineer Trainee (GET)',
    ctc: '₹ 6.5 LPA',
    ctcNum: 6.5,
    driveDate: '2026-10-30',
    deadline: '2026-10-24',
    venue: 'Mechanical Workshop Hall & Placement Cell',
    eligibility: 'B.Tech MECH, CIVIL, EEE, ECE · Min 6.0 CGPA',
    rounds: 'Aptitude Test, Core Technical Round, Director Interview',
    status: 'Upcoming',
    eligibleBranches: ['MECH', 'CIVIL', 'EEE', 'ECE'],
    applicantsCount: 130,
    shortlistedCount: 40,
    selectedCount: 16,
    minCgpa: 6.0,
    description: 'Industrial automation, structural robotics, CAD/CAM simulation, and green energy infrastructure projects.',
  },
  {
    id: 'DRV-107',
    title: 'Deloitte Analyst - Consulting & Cyber',
    company: 'Deloitte USI',
    tier: 'Dream',
    role: 'Technology Analyst - Cloud Security',
    ctc: '₹ 9.2 LPA',
    ctcNum: 9.2,
    driveDate: '2026-10-12',
    deadline: '2026-10-09',
    venue: 'Campus Conference Hall & Zoom',
    eligibility: 'B.Tech All Branches · Min 7.0 CGPA · Excellent communication',
    rounds: 'Cognitive & Technical Assessment, Case Study Interview, Partner Round',
    status: 'Active',
    eligibleBranches: ['CSE', 'IT', 'ECE', 'EEE', 'MECH'],
    applicantsCount: 220,
    shortlistedCount: 65,
    selectedCount: 24,
    minCgpa: 7.0,
    description: 'Risk advisory, cybersecurity defense, cloud transformation, and enterprise architecture consulting.',
  },
  {
    id: 'DRV-108',
    title: 'Infosys Power Programmer & Specialist',
    company: 'Infosys',
    tier: 'Dream',
    role: 'Specialist Programmer (SP)',
    ctc: '₹ 9.5 LPA',
    ctcNum: 9.5,
    driveDate: '2026-09-18',
    deadline: '2026-09-12',
    venue: 'Virtual Platform (Infosys Springboard)',
    eligibility: 'B.Tech CSE, IT, ECE · Min 7.0 CGPA',
    rounds: 'InfyTQ Advanced Coding, Technical Interview, HR Round',
    status: 'Completed',
    eligibleBranches: ['CSE', 'IT', 'ECE'],
    applicantsCount: 165,
    shortlistedCount: 52,
    selectedCount: 18,
    minCgpa: 7.0,
    description: 'High-performance coding role working directly on deep-tech innovation labs, fintech platforms, and generative AI apps.',
  },
]

export const defaultCompanies = [
  {
    id: 'CMP-01',
    name: 'Microsoft India',
    industry: 'Cloud & Enterprise Software',
    tier: 'Super Dream',
    hq: 'Hyderabad / Bengaluru / Redmond',
    contactPerson: 'Radhika Sharma',
    contactEmail: 'r.sharma@microsoft.com',
    contactPhone: '+91 98450 11223',
    website: 'https://careers.microsoft.com',
    mouSigned: true,
    pastHires: 36,
    avgPackage: '₹ 44.0 LPA',
    status: 'Active Partner',
    notes: 'Primary recruiter for Tier-1 coding talent. Prefers hands-on cloud projects.',
  },
  {
    id: 'CMP-02',
    name: 'Google',
    industry: 'Internet & Artificial Intelligence',
    tier: 'Super Dream',
    hq: 'Bengaluru / Mountain View',
    contactPerson: 'Arunav Sengupta',
    contactEmail: 'arunav.s@google.com',
    contactPhone: '+91 98200 44321',
    website: 'https://careers.google.com',
    mouSigned: true,
    pastHires: 18,
    avgPackage: '₹ 42.0 LPA',
    status: 'Active Partner',
    notes: 'Recruits annually for core SWE. Focuses on data structures and algorithms.',
  },
  {
    id: 'CMP-03',
    name: 'Amazon',
    industry: 'E-commerce & Cloud Computing',
    tier: 'Super Dream',
    hq: 'Hyderabad / Seattle',
    contactPerson: 'Deepika Nair',
    contactEmail: 'nairdeep@amazon.com',
    contactPhone: '+91 97411 88990',
    website: 'https://amazon.jobs',
    mouSigned: true,
    pastHires: 48,
    avgPackage: '₹ 32.0 LPA',
    status: 'Active Partner',
    notes: 'Regular on-campus visits. Emphasizes leadership principles and system scalability.',
  },
  {
    id: 'CMP-04',
    name: 'Qualcomm',
    industry: 'Semiconductors & Telecommunications',
    tier: 'Super Dream',
    hq: 'Hyderabad / San Diego',
    contactPerson: 'K. V. Subbarao',
    contactEmail: 'subbarao.kv@qualcomm.com',
    contactPhone: '+91 94401 55667',
    website: 'https://www.qualcomm.com/careers',
    mouSigned: true,
    pastHires: 24,
    avgPackage: '₹ 24.5 LPA',
    status: 'Active Partner',
    notes: 'Key partner for ECE & EEE embedded systems and FPGA design.',
  },
  {
    id: 'CMP-05',
    name: 'Deloitte USI',
    industry: 'Consulting & Technology Services',
    tier: 'Dream',
    hq: 'Hyderabad / New York',
    contactPerson: 'Farhan Akhtar',
    contactEmail: 'fa.recruiter@deloitte.com',
    contactPhone: '+91 99887 66554',
    website: 'https://www2.deloitte.com/careers',
    mouSigned: true,
    pastHires: 72,
    avgPackage: '₹ 9.2 LPA',
    status: 'Active Partner',
    notes: 'Multi-stream recruitment across CSE, IT, ECE, MECH for digital consulting.',
  },
  {
    id: 'CMP-06',
    name: 'Tata Consultancy Services',
    industry: 'IT Services & Consulting',
    tier: 'Dream',
    hq: 'Mumbai / Hyderabad',
    contactPerson: 'Sudhakar Rao',
    contactEmail: 'sudhakar.r@tcs.com',
    contactPhone: '+91 94900 22334',
    website: 'https://www.tcs.com/careers',
    mouSigned: true,
    pastHires: 180,
    avgPackage: '₹ 7.5 LPA',
    status: 'Active Partner',
    notes: 'Largest single recruiter. Offers Digital, Prime, and Ninja hiring bands.',
  },
  {
    id: 'CMP-07',
    name: 'L&T Technology Services',
    industry: 'Engineering R&D Services',
    tier: 'Core',
    hq: 'Vadodara / Chennai',
    contactPerson: 'B. Maheshwar',
    contactEmail: 'b.maheshwar@ltts.com',
    contactPhone: '+91 98334 11229',
    website: 'https://www.ltts.com/careers',
    mouSigned: true,
    pastHires: 55,
    avgPackage: '₹ 6.5 LPA',
    status: 'Active Partner',
    notes: 'Core recruiter for Mechanical, Civil, and Electrical streams.',
  },
  {
    id: 'CMP-08',
    name: 'Infosys',
    industry: 'IT Services & Digital Platforms',
    tier: 'Dream',
    hq: 'Bengaluru / Hyderabad',
    contactPerson: 'Sneha Kulkarni',
    contactEmail: 'sneha_k@infosys.com',
    contactPhone: '+91 98112 33445',
    website: 'https://www.infosys.com/careers',
    mouSigned: true,
    pastHires: 125,
    avgPackage: '₹ 9.5 LPA',
    status: 'Active Partner',
    notes: 'Specialist Programmer (SP) and Digital Specialist Engineer (DSE) hires.',
  },
]

export const defaultApplications = [
  {
    id: 'APP-501',
    studentName: 'Venkata Sai Kumar',
    rollNo: '21B81A0501',
    branch: 'CSE',
    cgpa: 8.92,
    driveId: 'DRV-101',
    company: 'Microsoft India',
    role: 'Software Engineer - Cloud & AI',
    appliedDate: '2026-10-05',
    status: 'Shortlisted',
    email: 'saikumar.v@college.edu',
    phone: '+91 98765 43210',
    resumeUrl: 'Venkata_Sai_Resume.pdf',
    currentRound: 'Tech Round 1',
  },
  {
    id: 'APP-502',
    studentName: 'Kavitha Ranganathan',
    rollNo: '21B81A0518',
    branch: 'CSE',
    cgpa: 9.35,
    driveId: 'DRV-101',
    company: 'Microsoft India',
    role: 'Software Engineer - Cloud & AI',
    appliedDate: '2026-10-06',
    status: 'Shortlisted',
    email: 'kavitha.r@college.edu',
    phone: '+91 98765 43211',
    resumeUrl: 'Kavitha_R_Resume.pdf',
    currentRound: 'Tech Round 2',
  },
  {
    id: 'APP-503',
    studentName: 'Naveen Krishna M',
    rollNo: '21B81A0412',
    branch: 'ECE',
    cgpa: 8.45,
    driveId: 'DRV-104',
    company: 'Qualcomm',
    role: 'Firmware & Embedded Systems Engineer',
    appliedDate: '2026-10-08',
    status: 'Interviewing',
    email: 'naveen.k@college.edu',
    phone: '+91 98765 43212',
    resumeUrl: 'Naveen_Krishna_Resume.pdf',
    currentRound: 'System Architecture',
  },
  {
    id: 'APP-504',
    studentName: 'B. Harish Varma',
    rollNo: '21B81A1205',
    branch: 'IT',
    cgpa: 7.85,
    driveId: 'DRV-107',
    company: 'Deloitte USI',
    role: 'Technology Analyst - Cloud Security',
    appliedDate: '2026-10-07',
    status: 'Applied',
    email: 'harish.v@college.edu',
    phone: '+91 98765 43213',
    resumeUrl: 'Harish_Varma_Resume.pdf',
    currentRound: 'Aptitude Test',
  },
  {
    id: 'APP-505',
    studentName: 'Ananya Reddy',
    rollNo: '21B81A0512',
    branch: 'CSE',
    cgpa: 9.15,
    driveId: 'DRV-105',
    company: 'Amazon',
    role: 'Software Development Engineer - 1',
    appliedDate: '2026-09-20',
    status: 'Selected',
    email: 'ananya.r@college.edu',
    phone: '+91 98765 43214',
    resumeUrl: 'Ananya_Reddy_Resume.pdf',
    currentRound: 'Offer Released',
  },
  {
    id: 'APP-506',
    studentName: 'Rohit Balaji S',
    rollNo: '21B81A0322',
    branch: 'MECH',
    cgpa: 7.60,
    driveId: 'DRV-106',
    company: 'L&T Technology Services',
    role: 'Graduate Engineer Trainee (GET)',
    appliedDate: '2026-10-09',
    status: 'Applied',
    email: 'rohit.b@college.edu',
    phone: '+91 98765 43215',
    resumeUrl: 'Rohit_Balaji_Resume.pdf',
    currentRound: 'Aptitude Test',
  },
  {
    id: 'APP-507',
    studentName: 'Sanjay Dutt T',
    rollNo: '21B81A0589',
    branch: 'CSE',
    cgpa: 8.10,
    driveId: 'DRV-103',
    company: 'Tata Consultancy Services',
    role: 'Digital Engineer / Full Stack Developer',
    appliedDate: '2026-10-07',
    status: 'Interviewing',
    email: 'sanjay.d@college.edu',
    phone: '+91 98765 43216',
    resumeUrl: 'Sanjay_Dutt_Resume.pdf',
    currentRound: 'Tech Interview',
  },
  {
    id: 'APP-508',
    studentName: 'Sneha Madhav',
    rollNo: '21B81A0434',
    branch: 'ECE',
    cgpa: 8.70,
    driveId: 'DRV-104',
    company: 'Qualcomm',
    role: 'Firmware & Embedded Systems Engineer',
    appliedDate: '2026-10-08',
    status: 'Shortlisted',
    email: 'sneha.m@college.edu',
    phone: '+91 98765 43217',
    resumeUrl: 'Sneha_Madhav_Resume.pdf',
    currentRound: 'Tech Round 1',
  },
]

export const defaultInterviews = [
  {
    id: 'INT-301',
    candidateName: 'Priya Nambiar',
    rollNo: '21B81A0545',
    branch: 'CSE',
    company: 'Qualcomm',
    role: 'Firmware & Embedded Systems Engineer',
    roundType: 'Technical Round 1',
    start: '2026-10-18T10:30',
    end: '2026-10-18T11:15',
    venue: 'Placement Cell Lab 2 & G-Meet',
    interviewer: 'K. Srinivasan (Sr. Firmware Lead)',
    meetLink: 'https://meet.google.com/xyz-qcom-plc',
    status: 'Scheduled',
    feedback: 'Scheduled for Linux kernel device driver questions',
  },
  {
    id: 'INT-302',
    candidateName: 'Venkata Sai Kumar',
    rollNo: '21B81A0501',
    branch: 'CSE',
    company: 'Microsoft India',
    role: 'Software Engineer - Cloud & AI',
    roundType: 'Technical Round 1',
    start: '2026-10-25T11:00',
    end: '2026-10-25T11:45',
    venue: 'Microsoft Teams Link',
    interviewer: 'Amitav Das (Azure Principal SWE)',
    meetLink: 'https://teams.microsoft.com/l/meetup-join/101',
    status: 'Scheduled',
    feedback: 'High scoring in preliminary OA (100% test cases)',
  },
  {
    id: 'INT-303',
    candidateName: 'Kavitha Ranganathan',
    rollNo: '21B81A0518',
    branch: 'CSE',
    company: 'Microsoft India',
    role: 'Software Engineer - Cloud & AI',
    roundType: 'Technical Round 2',
    start: '2026-10-25T14:00',
    end: '2026-10-25T15:00',
    venue: 'Microsoft Teams Link',
    interviewer: 'S. Chandrasekar (Partner Architect)',
    meetLink: 'https://teams.microsoft.com/l/meetup-join/102',
    status: 'Scheduled',
    feedback: 'System Design: Distributed Cache & Event Store',
  },
  {
    id: 'INT-304',
    candidateName: 'B. Harish Varma',
    rollNo: '21B81A1205',
    branch: 'IT',
    company: 'Deloitte USI',
    role: 'Technology Analyst - Cloud Security',
    roundType: 'Managerial Round',
    start: '2026-10-12T15:30',
    end: '2026-10-12T16:15',
    venue: 'Seminar Hall 2 & Zoom',
    interviewer: 'Deepak Joshi (Director, Cyber Risk)',
    meetLink: 'https://deloitte.zoom.us/j/988776655',
    status: 'Cleared',
    feedback: 'Strong grasp of ISO 27001 and cloud IAM policies. Recommended for offer.',
  },
  {
    id: 'INT-305',
    candidateName: 'Sanjay Dutt T',
    rollNo: '21B81A0589',
    branch: 'CSE',
    company: 'Tata Consultancy Services',
    role: 'Digital Engineer / Full Stack Developer',
    roundType: 'HR & Managerial',
    start: '2026-10-14T16:00',
    end: '2026-10-14T16:30',
    venue: 'Placement Interview Room 1',
    interviewer: 'P. Meenakshi (TCS Talent Acquisition)',
    meetLink: '—',
    status: 'Cleared',
    feedback: 'Clear communication, positive attitude, open to relocation.',
  },
]

export const defaultOffers = [
  {
    id: 'OFR-201',
    studentName: 'Ananya Reddy',
    rollNo: '21B81A0512',
    branch: 'CSE',
    company: 'Amazon',
    role: 'Software Development Engineer - 1',
    ctc: '₹ 32.0 LPA',
    ctcNum: 32.0,
    offerDate: '2026-10-02',
    deadline: '2026-10-22',
    offerLetterRef: 'AMZ-HYD-2026-0419',
    status: 'Accepted',
    location: 'Hyderabad',
  },
  {
    id: 'OFR-202',
    studentName: 'M. Tarun Teja',
    rollNo: '21B81A0529',
    branch: 'CSE',
    company: 'Amazon',
    role: 'Software Development Engineer - 1',
    ctc: '₹ 32.0 LPA',
    ctcNum: 32.0,
    offerDate: '2026-10-02',
    deadline: '2026-10-22',
    offerLetterRef: 'AMZ-HYD-2026-0420',
    status: 'Accepted',
    location: 'Bengaluru',
  },
  {
    id: 'OFR-203',
    studentName: 'Sravani Gottipati',
    rollNo: '21B81A1211',
    branch: 'IT',
    company: 'Infosys',
    role: 'Specialist Programmer (SP)',
    ctc: '₹ 9.5 LPA',
    ctcNum: 9.5,
    offerDate: '2026-09-24',
    deadline: '2026-10-14',
    offerLetterRef: 'INFY-SP-2026-1082',
    status: 'Accepted',
    location: 'Pune',
  },
  {
    id: 'OFR-204',
    studentName: 'Rahul Dev Verma',
    rollNo: '21B81A0419',
    branch: 'ECE',
    company: 'Infosys',
    role: 'Specialist Programmer (SP)',
    ctc: '₹ 9.5 LPA',
    ctcNum: 9.5,
    offerDate: '2026-09-24',
    deadline: '2026-10-14',
    offerLetterRef: 'INFY-SP-2026-1083',
    status: 'Pending',
    location: 'Hyderabad',
  },
  {
    id: 'OFR-205',
    studentName: 'B. Harish Varma',
    rollNo: '21B81A1205',
    branch: 'IT',
    company: 'Deloitte USI',
    role: 'Technology Analyst - Cloud Security',
    ctc: '₹ 9.2 LPA',
    ctcNum: 9.2,
    offerDate: '2026-10-13',
    deadline: '2026-10-30',
    offerLetterRef: 'DEL-USI-2026-8841',
    status: 'Accepted',
    location: 'Hyderabad',
  },
  {
    id: 'OFR-206',
    studentName: 'Sanjay Dutt T',
    rollNo: '21B81A0589',
    branch: 'CSE',
    company: 'Tata Consultancy Services',
    role: 'Digital Engineer / Full Stack Developer',
    ctc: '₹ 7.5 LPA',
    ctcNum: 7.5,
    offerDate: '2026-10-15',
    deadline: '2026-10-29',
    offerLetterRef: 'TCS-DIG-2026-9041',
    status: 'Accepted',
    location: 'Chennai',
  },
]

export const defaultPlacementStats = {
  totalEligible: 420,
  totalPlaced: 326,
  placementRate: 77.6,
  averagePackage: '₹ 7.8 LPA',
  highestPackage: '₹ 44.0 LPA',
  medianPackage: '₹ 6.5 LPA',
  totalOffers: 395,
  branchStats: [
    { branch: 'CSE', eligible: 148, placed: 142, rate: 95.9, avg: '₹ 11.2 LPA', highest: '₹ 44.0 LPA' },
    { branch: 'IT', eligible: 60, placed: 55, rate: 91.7, avg: '₹ 8.8 LPA', highest: '₹ 32.0 LPA' },
    { branch: 'ECE', eligible: 92, placed: 78, rate: 84.8, avg: '₹ 7.4 LPA', highest: '₹ 24.5 LPA' },
    { branch: 'MECH', eligible: 60, placed: 41, rate: 68.3, avg: '₹ 5.8 LPA', highest: '₹ 9.2 LPA' },
    { branch: 'CIVIL', eligible: 60, placed: 36, rate: 60.0, avg: '₹ 5.2 LPA', highest: '₹ 7.5 LPA' },
  ],
  tierBreakdown: [
    { tier: 'Super Dream (> ₹ 15 LPA)', offers: 48, percentage: 12.2, color: '#8b5cf6' },
    { tier: 'Dream (₹ 8 - ₹ 15 LPA)', offers: 112, percentage: 28.4, color: '#3b82f6' },
    { tier: 'Core / Standard (₹ 4 - ₹ 8 LPA)', offers: 235, percentage: 59.4, color: '#10b981' },
  ],
}
