export const defaultMeetings = [
  {
    id: 'meet-001',
    title: 'Academic Council Quarterly Review (Q1)',
    category: 'Academic Council',
    start: '2026-10-15T10:00',
    end: '2026-10-15T12:30',
    venue: 'Executive Boardroom, Admin Block',
    organizer: 'Dr. K. V. Raman (Dean Academics)',
    audience: 'Faculty',
    agenda: 'Review of R22 regulation electives, NEP 2020 credit allocation, and finalization of odd semester exam schedule.',
    status: 'Upcoming',
  },
  {
    id: 'meet-002',
    title: 'CSE Department Faculty & Curriculum Review',
    category: 'Department',
    start: '2026-10-12T14:30',
    end: '2026-10-12T16:00',
    venue: 'Seminar Hall 1, CSE Block',
    organizer: 'Prof. Ananya Sen (HOD CSE)',
    agenda: 'AI/ML lab equipment procurement, final year capstone project guidelines, and NBA accreditation mock audit.',
    audience: 'Faculty',
    status: 'Upcoming',
  },
  {
    id: 'meet-003',
    title: 'Anti-Ragging & Campus Discipline Committee',
    category: 'Committee',
    start: '2026-10-09T11:00',
    end: '2026-10-09T12:00',
    venue: 'Conference Room 2',
    organizer: 'Prof. R. M. Reddy (Chief Proctor)',
    agenda: 'Hostel inspection report review, student squad duties assignment, and orientation helpline readiness.',
    audience: 'Both',
    status: 'In Progress',
  },
  {
    id: 'meet-004',
    title: 'Industry Advisory Board (IAB) Annual Meet',
    category: 'Industry Relations',
    start: '2026-10-22T10:30',
    end: '2026-10-22T13:30',
    venue: 'Auditorium Hall B & Hybrid Webex',
    organizer: 'Dr. S. K. Murthy (Director, Placements & IIPC)',
    agenda: 'Curriculum industry-alignment, mandatory 8th semester internships, and corporate guest lecture calendar.',
    audience: 'Faculty',
    status: 'Upcoming',
  },
  {
    id: 'meet-005',
    title: 'IQAC Internal Quality Audit Preparation',
    category: 'IQAC',
    start: '2026-10-04T15:00',
    end: '2026-10-04T17:00',
    venue: 'IQAC Meeting Room, 2nd Floor',
    organizer: 'Dr. P. Swaminathan (IQAC Coordinator)',
    agenda: 'Department files verification, student feedback score consolidation, and NAAC metric tracking.',
    audience: 'Faculty',
    status: 'Completed',
  },
]

export const defaultEvents = [
  {
    id: 'evt-001',
    title: 'TechNovation 2026: National 36-Hr Hackathon',
    category: 'Technical',
    start: '2026-10-24T09:00',
    end: '2026-10-25T21:00',
    venue: 'Main Campus Auditorium & Innovation Hub',
    organizer: 'Centre for Innovation & Incubation (CII)',
    capacity: 250,
    registeredCount: 218,
    deadline: '2026-10-20T23:59',
    description: 'Premier inter-college coding marathon solving real-world challenges in AI, CleanTech, Web3, and Smart Mobility with cash prizes of ₹1.5 Lakhs.',
    status: 'Upcoming',
  },
  {
    id: 'evt-002',
    title: 'Hands-on Workshop: Generative AI & Cloud Native Microservices',
    category: 'Workshop',
    start: '2026-10-18T09:30',
    end: '2026-10-18T16:30',
    venue: 'Advanced Computing Lab 3',
    organizer: 'Dept. of CSE & Google Developer Student Club',
    capacity: 120,
    registeredCount: 114,
    deadline: '2026-10-16T18:00',
    description: 'Deep dive into LLM deployment, Docker containerization, Kubernetes orchestration, and vector search with expert engineers from AWS and Google Cloud.',
    status: 'Upcoming',
  },
  {
    id: 'evt-003',
    title: 'Campus Placement Orientation & Mock Technical Drives',
    category: 'Career',
    start: '2026-10-14T10:00',
    end: '2026-10-14T17:00',
    venue: 'Open Air Amphitheatre',
    organizer: 'Training & Placement Cell (T&P)',
    capacity: 500,
    registeredCount: 480,
    deadline: '2026-10-13T12:00',
    description: 'Comprehensive orientation for 3rd and 4th-year B.Tech students on campus recruitment patterns, ATS resumes, and mock HR rounds.',
    status: 'Upcoming',
  },
  {
    id: 'evt-004',
    title: 'Alumni Conclave & Mentorship Summit 2026',
    category: 'Networking',
    start: '2026-10-28T11:00',
    end: '2026-10-28T16:00',
    venue: 'Silver Jubilee Auditorium',
    organizer: 'Alumni Relations Committee',
    capacity: 350,
    registeredCount: 295,
    deadline: '2026-10-25T18:00',
    description: 'Engage with distinguished alumni working across global tech leaders. Interactive panel discussions and 1-on-1 career guidance.',
    status: 'Upcoming',
  },
  {
    id: 'evt-005',
    title: 'AURA 2026 - Inter-Collegiate Annual Sports Meet',
    category: 'Sports',
    start: '2026-10-02T08:00',
    end: '2026-10-04T18:00',
    venue: 'University Sports Complex & Athletics Ground',
    organizer: 'Dept. of Physical Education',
    capacity: 600,
    registeredCount: 590,
    deadline: '2026-09-30T17:00',
    description: 'Annual flagship athletics, cricket, football, basketball, and badminton championships spanning 3 days of competitive spirit.',
    status: 'Completed',
  },
]

export const defaultRegistrations = [
  {
    id: 'reg-101',
    eventId: 'evt-001',
    eventTitle: 'TechNovation 2026: National 36-Hr Hackathon',
    studentName: 'Aarav Varma',
    rollNumber: '22CS014',
    department: 'Computer Science and Engineering',
    year: '3rd Year',
    registeredAt: '2026-10-06 14:22',
    status: 'Confirmed',
    ticketCode: 'TNV-2026-014',
  },
  {
    id: 'reg-102',
    eventId: 'evt-001',
    eventTitle: 'TechNovation 2026: National 36-Hr Hackathon',
    studentName: 'Pooja Hegde',
    rollNumber: '22IT045',
    department: 'Information Technology',
    year: '3rd Year',
    registeredAt: '2026-10-06 15:10',
    status: 'Confirmed',
    ticketCode: 'TNV-2026-045',
  },
  {
    id: 'reg-103',
    eventId: 'evt-002',
    eventTitle: 'Hands-on Workshop: Generative AI & Cloud Native Microservices',
    studentName: 'Karthik Rao',
    rollNumber: '23EC089',
    department: 'Electronics and Communication Engineering',
    year: '2nd Year',
    registeredAt: '2026-10-07 09:45',
    status: 'Confirmed',
    ticketCode: 'GAI-2026-089',
  },
  {
    id: 'reg-104',
    eventId: 'evt-002',
    eventTitle: 'Hands-on Workshop: Generative AI & Cloud Native Microservices',
    studentName: 'Sneha Patel',
    rollNumber: '22CS112',
    department: 'Computer Science and Engineering',
    year: '3rd Year',
    registeredAt: '2026-10-07 11:20',
    status: 'Confirmed',
    ticketCode: 'GAI-2026-112',
  },
  {
    id: 'reg-105',
    eventId: 'evt-003',
    eventTitle: 'Campus Placement Orientation & Mock Technical Drives',
    studentName: 'Rohan Deshmukh',
    rollNumber: '21ME032',
    department: 'Mechanical Engineering',
    year: '4th Year',
    registeredAt: '2026-10-08 10:05',
    status: 'Confirmed',
    ticketCode: 'CPO-2026-032',
  },
  {
    id: 'reg-106',
    eventId: 'evt-001',
    eventTitle: 'TechNovation 2026: National 36-Hr Hackathon',
    studentName: 'Divya Nair',
    rollNumber: '22EE021',
    department: 'Electrical and Electronics Engineering',
    year: '3rd Year',
    registeredAt: '2026-10-08 16:30',
    status: 'Waitlisted',
    ticketCode: 'TNV-2026-W02',
  },
]

export const defaultAttendance = [
  {
    id: 'att-201',
    activityType: 'Meeting',
    activityTitle: 'CSE Department Faculty & Curriculum Review',
    participantName: 'Dr. Suresh Chandra',
    participantRole: 'Faculty (Associate Prof)',
    department: 'CSE',
    status: 'Present',
    checkInTime: '2026-10-12 14:25',
    mode: 'RFID Tap',
  },
  {
    id: 'att-202',
    activityType: 'Meeting',
    activityTitle: 'Anti-Ragging & Campus Discipline Committee',
    participantName: 'Prof. R. M. Reddy',
    participantRole: 'Faculty (HOD EEE)',
    department: 'EEE',
    status: 'Present',
    checkInTime: '2026-10-09 10:55',
    mode: 'Manual Verification',
  },
  {
    id: 'att-203',
    activityType: 'Meeting',
    activityTitle: 'Anti-Ragging & Campus Discipline Committee',
    participantName: 'Kavya Madhavan',
    participantRole: 'Student Representative',
    department: 'ECE',
    status: 'Present',
    checkInTime: '2026-10-09 11:02',
    mode: 'QR Scan',
  },
  {
    id: 'att-204',
    activityType: 'Event',
    activityTitle: 'AURA 2026 - Inter-Collegiate Annual Sports Meet',
    participantName: 'Aarav Varma',
    participantRole: 'Student Athlete',
    department: 'CSE',
    status: 'Present',
    checkInTime: '2026-10-02 08:15',
    mode: 'Biometric Pass',
  },
  {
    id: 'att-205',
    activityType: 'Event',
    activityTitle: 'AURA 2026 - Inter-Collegiate Annual Sports Meet',
    participantName: 'Naveen Kumar',
    participantRole: 'Student',
    department: 'MECH',
    status: 'Absent',
    checkInTime: '—',
    mode: 'Unreported',
  },
  {
    id: 'att-206',
    activityType: 'Meeting',
    activityTitle: 'IQAC Internal Quality Audit Preparation',
    participantName: 'Dr. Priya V.',
    participantRole: 'Faculty (Assistant Prof)',
    department: 'Civil Engg',
    status: 'Present',
    checkInTime: '2026-10-04 14:58',
    mode: 'RFID Tap',
  },
]

export const defaultMinutes = [
  {
    id: 'mom-301',
    meetingTitle: 'Academic Council Quarterly Review (Q1)',
    meetingDate: '2026-10-15',
    decisionSummary: 'Approved 2 credits mandatory industry certification for 6th-semester CSE/IT students. Finalized lab exam dates before semester end.',
    actionItem: 'Draft AICTE compliant curriculum matrix and circulate to all Department HODs.',
    owner: 'Dean Academics Office',
    dueDate: '2026-10-25',
    priority: 'High',
    completed: false,
  },
  {
    id: 'mom-302',
    meetingTitle: 'CSE Department Faculty & Curriculum Review',
    meetingDate: '2026-10-12',
    decisionSummary: 'Recommended purchase of 40 GPU workstations for new Deep Learning lab. Formed student mentoring committees for weak learners.',
    actionItem: 'Submit lab vendor quotation and power backup requirements to Principal Office.',
    owner: 'Prof. Ananya Sen (HOD CSE)',
    dueDate: '2026-10-20',
    priority: 'High',
    completed: true,
  },
  {
    id: 'mom-303',
    meetingTitle: 'Anti-Ragging & Campus Discipline Committee',
    meetingDate: '2026-10-09',
    decisionSummary: 'Zero incidents recorded for fresh batch 2026-27. Hostel security squads to maintain daily evening logbooks.',
    actionItem: 'Install 4 additional CCTV cameras near junior hostel cafeteria entrance.',
    owner: 'Estate Officer & Chief Proctor',
    dueDate: '2026-10-18',
    priority: 'Medium',
    completed: false,
  },
  {
    id: 'mom-304',
    meetingTitle: 'Industry Advisory Board (IAB) Annual Meet',
    meetingDate: '2026-10-22',
    decisionSummary: 'Industry partners agreed to offer 150+ internship slots for winter break. Finalized guest speaker lineup for semester.',
    actionItem: 'Consolidate student skill profiles and share with signed partner companies.',
    owner: 'Training & Placement Officer',
    dueDate: '2026-11-05',
    priority: 'Medium',
    completed: false,
  },
  {
    id: 'mom-305',
    meetingTitle: 'IQAC Internal Quality Audit Preparation',
    meetingDate: '2026-10-04',
    decisionSummary: 'All departments scored over 88% in internal documentation audit. Identified 3 departments requiring course-file updates.',
    actionItem: 'Upload revised faculty course files to CMS digital repository before external NAAC visit.',
    owner: 'All Department NAAC Coordinators',
    dueDate: '2026-10-14',
    priority: 'Low',
    completed: true,
  },
]
