export const defaultBooks = [
  {
    id: 'book-001',
    title: 'Introduction to Algorithms (4th Edition)',
    author: 'Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein',
    isbn: '978-0262046305',
    category: 'Computer Science & AI',
    department: 'CSE',
    publisher: 'MIT Press',
    edition: '4th Edition (2022)',
    subject: 'Data Structures & Algorithms',
    language: 'English',
    rack: 'Rack CS-04 / Shelf B',
    totalCopies: 12,
    availableCopies: 7,
    issuedCopies: 5,
    rating: 4.9,
    coverColor: '#1e3a8a',
    accentColor: '#3b82f6',
    callNumber: 'QA76.6 .C662 2022',
    description: 'The standard collegiate reference on algorithmic analysis, dynamic programming, graph algorithms, and computational complexity theory.',
  },
  {
    id: 'book-002',
    title: 'Operating System Concepts (10th Edition)',
    author: 'Abraham Silberschatz, Peter B. Galvin, Greg Gagne',
    isbn: '978-1119800361',
    category: 'Computer Science & AI',
    department: 'CSE',
    publisher: 'Wiley',
    edition: '10th Edition (2021)',
    subject: 'Operating Systems & Virtualization',
    language: 'English',
    rack: 'Rack CS-02 / Shelf A',
    totalCopies: 10,
    availableCopies: 4,
    issuedCopies: 6,
    rating: 4.8,
    coverColor: '#0f766e',
    accentColor: '#14b8a6',
    callNumber: 'QA76.76.O63 S558',
    description: 'The classic "Dinosaur book" covering process synchronization, memory virtualization, distributed systems, and modern kernel architectures.',
  },
  {
    id: 'book-003',
    title: 'Artificial Intelligence: A Modern Approach',
    author: 'Stuart Russell, Peter Norvig',
    isbn: '978-0134610993',
    category: 'Computer Science & AI',
    department: 'AIML',
    publisher: 'Pearson',
    edition: '4th Global Edition',
    subject: 'Artificial Intelligence & Robotics',
    language: 'English',
    rack: 'Rack CS-06 / Shelf C',
    totalCopies: 8,
    availableCopies: 2,
    issuedCopies: 6,
    rating: 4.9,
    coverColor: '#581c87',
    accentColor: '#a855f7',
    callNumber: 'Q335 .R86 2020',
    description: 'Authoritative guide to intelligent agents, heuristic search, probabilistic reasoning, machine learning, deep learning, and NLP.',
  },
  {
    id: 'book-004',
    title: 'Computer Networks (6th Edition)',
    author: 'Andrew S. Tanenbaum, David J. Wetherall, Nick Feamster',
    isbn: '978-0137523658',
    category: 'Computer Science & AI',
    department: 'CSE',
    publisher: 'Pearson',
    edition: '6th Edition',
    subject: 'Computer Networking & Protocols',
    language: 'English',
    rack: 'Rack CS-03 / Shelf D',
    totalCopies: 14,
    availableCopies: 9,
    issuedCopies: 5,
    rating: 4.7,
    coverColor: '#0369a1',
    accentColor: '#0ea5e9',
    callNumber: 'TK5105.5 .T36',
    description: 'Comprehensive study of network layers from physical transmission to TCP/IP, modern SDN, cloud infrastructures, and network security.',
  },
  {
    id: 'book-005',
    title: 'Database System Concepts (7th Edition)',
    author: 'Abraham Silberschatz, Henry F. Korth, S. Sudarshan',
    isbn: '978-0078022159',
    category: 'Computer Science & AI',
    department: 'IT',
    publisher: 'McGraw-Hill Education',
    edition: '7th Edition',
    subject: 'Database Management Systems',
    language: 'English',
    rack: 'Rack CS-01 / Shelf C',
    totalCopies: 15,
    availableCopies: 8,
    issuedCopies: 7,
    rating: 4.7,
    coverColor: '#15803d',
    accentColor: '#22c55e',
    callNumber: 'QA76.9.D3 S56',
    description: 'Fundamentals of relational models, SQL queries, transaction management, indexing, distributed NoSQL databases, and query optimization.',
  },
  {
    id: 'book-006',
    title: 'Microelectronic Circuits (8th Edition)',
    author: 'Adel S. Sedra, Kenneth C. Smith, Tony Chan Carusone',
    isbn: '978-0190853464',
    category: 'Electronics & Communication',
    department: 'ECE',
    publisher: 'Oxford University Press',
    edition: '8th Edition',
    subject: 'Analog & Digital Electronics',
    language: 'English',
    rack: 'Rack EC-02 / Shelf B',
    totalCopies: 10,
    availableCopies: 6,
    issuedCopies: 4,
    rating: 4.8,
    coverColor: '#c2410c',
    accentColor: '#f97316',
    callNumber: 'TK7867 .S4 2020',
    description: 'Definitive textbook on solid-state devices, MOSFET amplifier design, frequency response, CMOS logic gates, and integrated circuit design.',
  },
  {
    id: 'book-007',
    title: 'Signals and Systems (2nd Edition)',
    author: 'Alan V. Oppenheim, Alan S. Willsky, S. Hamid Nawab',
    isbn: '978-0138147570',
    category: 'Electronics & Communication',
    department: 'ECE',
    publisher: 'Prentice Hall',
    edition: '2nd Edition',
    subject: 'Signal Processing',
    language: 'English',
    rack: 'Rack EC-05 / Shelf A',
    totalCopies: 9,
    availableCopies: 5,
    issuedCopies: 4,
    rating: 4.6,
    coverColor: '#b45309',
    accentColor: '#f59e0b',
    callNumber: 'QA402 .O66',
    description: 'Continuous-time and discrete-time signals, Fourier analysis, Laplace and Z-transforms, linear time-invariant systems, and filtering.',
  },
  {
    id: 'book-008',
    title: 'Electric Machinery Fundamentals (5th Edition)',
    author: 'Stephen J. Chapman',
    isbn: '978-0073529547',
    category: 'Electrical & Power',
    department: 'EEE',
    publisher: 'McGraw-Hill Education',
    edition: '5th Edition',
    subject: 'Electrical Machines & Transformers',
    language: 'English',
    rack: 'Rack EE-01 / Shelf B',
    totalCopies: 7,
    availableCopies: 4,
    issuedCopies: 3,
    rating: 4.7,
    coverColor: '#854d0e',
    accentColor: '#eab308',
    callNumber: 'TK2000 .C47',
    description: 'Principles of transformers, AC generators, synchronous motors, induction machines, and DC drive characteristics with MATLAB examples.',
  },
  {
    id: 'book-009',
    title: 'Engineering Mechanics: Dynamics (14th Edition)',
    author: 'Russell C. Hibbeler',
    isbn: '978-0133915389',
    category: 'Mechanical Engineering',
    department: 'MECH',
    publisher: 'Pearson',
    edition: '14th Edition',
    subject: 'Engineering Mechanics & Dynamics',
    language: 'English',
    rack: 'Rack ME-03 / Shelf C',
    totalCopies: 8,
    availableCopies: 5,
    issuedCopies: 3,
    rating: 4.5,
    coverColor: '#b91c1c',
    accentColor: '#ef4444',
    callNumber: 'TA352 .H53 2016',
    description: 'Kinematics and kinetics of particles, planar kinematics of rigid bodies, work and energy theorems, and mechanical vibrations.',
  },
  {
    id: 'book-010',
    title: 'Higher Engineering Mathematics (44th Edition)',
    author: 'Dr. B. S. Grewal',
    isbn: '978-8193328491',
    category: 'Basic Sciences & Mathematics',
    department: 'H&S',
    publisher: 'Khanna Publishers',
    edition: '44th Edition (2021)',
    subject: 'Applied Mathematics & Calculus',
    language: 'English',
    rack: 'Rack BS-01 / Shelf A',
    totalCopies: 25,
    availableCopies: 14,
    issuedCopies: 11,
    rating: 4.8,
    coverColor: '#1e293b',
    accentColor: '#64748b',
    callNumber: 'QA37.2 .G74',
    description: 'Indispensable syllabus companion for differential calculus, linear algebra, vector calculus, Fourier transforms, and numerical methods.',
  },
  {
    id: 'book-011',
    title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    author: 'Robert C. Martin ("Uncle Bob")',
    isbn: '978-0132350884',
    category: 'Computer Science & AI',
    department: 'CSE',
    publisher: 'Prentice Hall',
    edition: '1st Edition',
    subject: 'Software Engineering Best Practices',
    language: 'English',
    rack: 'Rack CS-05 / Shelf A',
    totalCopies: 6,
    availableCopies: 2,
    issuedCopies: 4,
    rating: 4.9,
    coverColor: '#111827',
    accentColor: '#38bdf8',
    callNumber: 'QA76.76.D47 M37',
    description: 'Foundational principles of meaningful naming, functions, SOLID architecture, test-driven development, and graceful refactoring.',
  },
  {
    id: 'book-012',
    title: 'Reinforcement Learning: An Introduction (2nd Edition)',
    author: 'Richard S. Sutton, Andrew G. Barto',
    isbn: '978-0262039246',
    category: 'Computer Science & AI',
    department: 'AIML',
    publisher: 'MIT Press',
    edition: '2nd Edition (2018)',
    subject: 'Machine Learning & Deep RL',
    language: 'English',
    rack: 'Rack CS-07 / Shelf B',
    totalCopies: 5,
    availableCopies: 1,
    issuedCopies: 4,
    rating: 4.9,
    coverColor: '#431407',
    accentColor: '#f97316',
    callNumber: 'Q325.6 .S88 2018',
    description: 'Key text on Markov Decision Processes, Monte Carlo methods, Temporal-Difference learning, policy gradients, and Deep Q-Networks.',
  },
]

export const defaultCopies = [
  { id: 'copy-001', bookId: 'book-001', accession: 'ACC-2026-0101', barcode: 'BC9821401', bookTitle: 'Introduction to Algorithms (4th Edition)', shelf: 'Rack CS-04 / Shelf B', condition: 'Good', status: 'Available', cost: 1850 },
  { id: 'copy-002', bookId: 'book-001', accession: 'ACC-2026-0102', barcode: 'BC9821402', bookTitle: 'Introduction to Algorithms (4th Edition)', shelf: 'Rack CS-04 / Shelf B', condition: 'Good', status: 'Available', cost: 1850 },
  { id: 'copy-003', bookId: 'book-001', accession: 'ACC-2026-0103', barcode: 'BC9821403', bookTitle: 'Introduction to Algorithms (4th Edition)', shelf: 'Rack CS-04 / Shelf B', condition: 'Worn', status: 'Issued', borrower: 'Aditya Varma (22CSE041)', cost: 1850 },
  { id: 'copy-004', bookId: 'book-001', accession: 'ACC-2026-0104', barcode: 'BC9821404', bookTitle: 'Introduction to Algorithms (4th Edition)', shelf: 'Rack CS-04 / Shelf B', condition: 'Good', status: 'Issued', borrower: 'Pooja Hegde (23CSE018)', cost: 1850 },
  { id: 'copy-005', bookId: 'book-002', accession: 'ACC-2026-0201', barcode: 'BC9821501', bookTitle: 'Operating System Concepts (10th Edition)', shelf: 'Rack CS-02 / Shelf A', condition: 'Good', status: 'Available', cost: 1420 },
  { id: 'copy-006', bookId: 'book-002', accession: 'ACC-2026-0202', barcode: 'BC9821502', bookTitle: 'Operating System Concepts (10th Edition)', shelf: 'Rack CS-02 / Shelf A', condition: 'Good', status: 'Issued', borrower: 'K. Sai Kiran (22IT012)', cost: 1420 },
  { id: 'copy-007', bookId: 'book-003', accession: 'ACC-2026-0301', barcode: 'BC9821601', bookTitle: 'Artificial Intelligence: A Modern Approach', shelf: 'Rack CS-06 / Shelf C', condition: 'Good', status: 'Issued', borrower: 'Dr. Ramesh Babu (Faculty ECE)', cost: 2400 },
  { id: 'copy-008', bookId: 'book-003', accession: 'ACC-2026-0302', barcode: 'BC9821602', bookTitle: 'Artificial Intelligence: A Modern Approach', shelf: 'Rack CS-06 / Shelf C', condition: 'Good', status: 'Available', cost: 2400 },
  { id: 'copy-009', bookId: 'book-004', accession: 'ACC-2026-0401', barcode: 'BC9821701', bookTitle: 'Computer Networks (6th Edition)', shelf: 'Rack CS-03 / Shelf D', condition: 'Good', status: 'Available', cost: 1350 },
  { id: 'copy-010', bookId: 'book-004', accession: 'ACC-2026-0402', barcode: 'BC9821702', bookTitle: 'Computer Networks (6th Edition)', shelf: 'Rack CS-03 / Shelf D', condition: 'Damaged', status: 'In Repair', cost: 1350 },
  { id: 'copy-011', bookId: 'book-005', accession: 'ACC-2026-0501', barcode: 'BC9821801', bookTitle: 'Database System Concepts (7th Edition)', shelf: 'Rack CS-01 / Shelf C', condition: 'Good', status: 'Available', cost: 1600 },
  { id: 'copy-012', bookId: 'book-006', accession: 'ACC-2026-0601', barcode: 'BC9821901', bookTitle: 'Microelectronic Circuits (8th Edition)', shelf: 'Rack EC-02 / Shelf B', condition: 'Good', status: 'Issued', borrower: 'Meghana Rao (23ECE055)', cost: 2100 },
  { id: 'copy-013', bookId: 'book-007', accession: 'ACC-2026-0701', barcode: 'BC9822001', bookTitle: 'Signals and Systems (2nd Edition)', shelf: 'Rack EC-05 / Shelf A', condition: 'Good', status: 'Available', cost: 1250 },
  { id: 'copy-014', bookId: 'book-010', accession: 'ACC-2026-1001', barcode: 'BC9822301', bookTitle: 'Higher Engineering Mathematics (44th Edition)', shelf: 'Rack BS-01 / Shelf A', condition: 'Good', status: 'Issued', borrower: 'Rahul Sharma (24MECH008)', cost: 890 },
  { id: 'copy-015', bookId: 'book-011', accession: 'ACC-2026-1101', barcode: 'BC9822401', bookTitle: 'Clean Code: A Handbook of Agile Software Craftsmanship', shelf: 'Rack CS-05 / Shelf A', condition: 'Good', status: 'Available', cost: 1100 },
]

export const defaultCirculation = [
  {
    id: 'circ-001',
    borrowerName: 'Aditya Varma',
    borrowerId: '22CSE041',
    borrowerType: 'Student',
    bookTitle: 'Introduction to Algorithms (4th Edition)',
    accession: 'ACC-2026-0103',
    barcode: 'BC9821403',
    issueDate: '2026-09-25',
    dueDate: '2026-10-09',
    status: 'Due Today',
    renewCount: 0,
    fineAccrued: 0,
  },
  {
    id: 'circ-002',
    borrowerName: 'Pooja Hegde',
    borrowerId: '23CSE018',
    borrowerType: 'Student',
    bookTitle: 'Introduction to Algorithms (4th Edition)',
    accession: 'ACC-2026-0104',
    barcode: 'BC9821404',
    issueDate: '2026-09-20',
    dueDate: '2026-10-04',
    status: 'Overdue',
    renewCount: 1,
    fineAccrued: 25,
  },
  {
    id: 'circ-003',
    borrowerName: 'K. Sai Kiran',
    borrowerId: '22IT012',
    borrowerType: 'Student',
    bookTitle: 'Operating System Concepts (10th Edition)',
    accession: 'ACC-2026-0202',
    barcode: 'BC9821502',
    issueDate: '2026-09-28',
    dueDate: '2026-10-12',
    status: 'Active',
    renewCount: 0,
    fineAccrued: 0,
  },
  {
    id: 'circ-004',
    borrowerName: 'Dr. Ramesh Babu',
    borrowerId: 'FAC-ECE-104',
    borrowerType: 'Faculty',
    bookTitle: 'Artificial Intelligence: A Modern Approach',
    accession: 'ACC-2026-0301',
    barcode: 'BC9821601',
    issueDate: '2026-09-10',
    dueDate: '2026-10-24',
    status: 'Active',
    renewCount: 0,
    fineAccrued: 0,
  },
  {
    id: 'circ-005',
    borrowerName: 'Meghana Rao',
    borrowerId: '23ECE055',
    borrowerType: 'Student',
    bookTitle: 'Microelectronic Circuits (8th Edition)',
    accession: 'ACC-2026-0601',
    barcode: 'BC9821901',
    issueDate: '2026-09-18',
    dueDate: '2026-10-02',
    status: 'Overdue',
    renewCount: 0,
    fineAccrued: 35,
  },
  {
    id: 'circ-006',
    borrowerName: 'Rahul Sharma',
    borrowerId: '24MECH008',
    borrowerType: 'Student',
    bookTitle: 'Higher Engineering Mathematics (44th Edition)',
    accession: 'ACC-2026-1001',
    barcode: 'BC9822301',
    issueDate: '2026-10-01',
    dueDate: '2026-10-15',
    status: 'Active',
    renewCount: 0,
    fineAccrued: 0,
  },
  {
    id: 'circ-007',
    borrowerName: 'Suresh Nambiar',
    borrowerId: '21CSE089',
    borrowerType: 'Student',
    bookTitle: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    accession: 'ACC-2026-1102',
    barcode: 'BC9822402',
    issueDate: '2026-10-03',
    dueDate: '2026-10-17',
    status: 'Active',
    renewCount: 0,
    fineAccrued: 0,
  },
]

export const defaultBorrowers = [
  { id: 'bor-001', name: 'Aditya Varma', code: '22CSE041', type: 'Student', department: 'CSE', year: '3rd Year', email: 'aditya.v@btech.ac.in', activeLoans: 1, maxLimit: 3, status: 'Active', finesPending: 0 },
  { id: 'bor-002', name: 'Pooja Hegde', code: '23CSE018', type: 'Student', department: 'CSE', year: '2nd Year', email: 'pooja.h@btech.ac.in', activeLoans: 1, maxLimit: 3, status: 'Active (Overdue)', finesPending: 25 },
  { id: 'bor-003', name: 'K. Sai Kiran', code: '22IT012', type: 'Student', department: 'IT', year: '3rd Year', email: 'saikiran.k@btech.ac.in', activeLoans: 1, maxLimit: 3, status: 'Active', finesPending: 0 },
  { id: 'bor-004', name: 'Dr. Ramesh Babu', code: 'FAC-ECE-104', type: 'Faculty', department: 'ECE', year: 'Professor', email: 'ramesh.b@btech.ac.in', activeLoans: 1, maxLimit: 6, status: 'Active', finesPending: 0 },
  { id: 'bor-005', name: 'Meghana Rao', code: '23ECE055', type: 'Student', department: 'ECE', year: '2nd Year', email: 'meghana.r@btech.ac.in', activeLoans: 1, maxLimit: 3, status: 'Active (Overdue)', finesPending: 35 },
  { id: 'bor-006', name: 'Rahul Sharma', code: '24MECH008', type: 'Student', department: 'MECH', year: '1st Year', email: 'rahul.s@btech.ac.in', activeLoans: 1, maxLimit: 3, status: 'Active', finesPending: 0 },
  { id: 'bor-007', name: 'Prof. Ananya Sen', code: 'FAC-CSE-002', type: 'Faculty', department: 'CSE', year: 'HOD CSE', email: 'ananya.sen@btech.ac.in', activeLoans: 2, maxLimit: 6, status: 'Active', finesPending: 0 },
  { id: 'bor-008', name: 'Sneha Patel', code: '22EEE034', type: 'Student', department: 'EEE', year: '3rd Year', email: 'sneha.p@btech.ac.in', activeLoans: 0, maxLimit: 3, status: 'Active', finesPending: 0 },
]

export const defaultReservations = [
  { id: 'res-001', borrowerName: 'Sneha Patel', borrowerId: '22EEE034', bookTitle: 'Artificial Intelligence: A Modern Approach', requestedOn: '2026-10-06', queuePosition: 1, status: 'Queued', priority: 'Standard' },
  { id: 'res-002', borrowerName: 'Gaurav Deshmukh', borrowerId: '23CSE090', bookTitle: 'Clean Code: A Handbook of Agile Software Craftsmanship', requestedOn: '2026-10-07', queuePosition: 1, status: 'Queued', priority: 'High' },
  { id: 'res-003', borrowerName: 'Divya Reddy', borrowerId: '22IT044', bookTitle: 'Introduction to Algorithms (4th Edition)', requestedOn: '2026-10-08', queuePosition: 2, status: 'Queued', priority: 'Standard' },
  { id: 'res-004', borrowerName: 'Vikas Gupta', borrowerId: '24ECE019', bookTitle: 'Operating System Concepts (10th Edition)', requestedOn: '2026-10-09', queuePosition: 1, status: 'Ready for Pickup', priority: 'High' },
]

export const defaultFines = [
  { id: 'fine-001', borrowerName: 'Meghana Rao', borrowerId: '23ECE055', accession: 'ACC-2026-0601', bookTitle: 'Microelectronic Circuits (8th Edition)', overdueDays: 7, fineAmount: 35, paymentStatus: 'Pending', calculatedOn: '2026-10-09' },
  { id: 'fine-002', borrowerName: 'Pooja Hegde', borrowerId: '23CSE018', accession: 'ACC-2026-0104', bookTitle: 'Introduction to Algorithms (4th Edition)', overdueDays: 5, fineAmount: 25, paymentStatus: 'Pending', calculatedOn: '2026-10-09' },
  { id: 'fine-003', borrowerName: 'Kunal Verma', borrowerId: '22MECH072', accession: 'ACC-2026-0910', bookTitle: 'Engineering Mechanics: Dynamics', overdueDays: 12, fineAmount: 60, paymentStatus: 'Paid', calculatedOn: '2026-10-02' },
  { id: 'fine-004', borrowerName: 'Rohit Shenoy', borrowerId: '21CSE110', accession: 'ACC-2026-0504', bookTitle: 'Database System Concepts (7th Edition)', overdueDays: 4, fineAmount: 20, paymentStatus: 'Paid', calculatedOn: '2026-09-28' },
]

export const defaultReports = [
  { id: 'rep-001', title: 'Monthly Circulation Audit (September 2026)', type: 'Circulation', generatedOn: '2026-10-01', period: 'Sep 1 - Sep 30, 2026', totalIssues: 412, totalReturns: 395, overdueRate: '4.1%', generatedBy: 'System Automation' },
  { id: 'rep-002', title: 'Lost & Damaged Books Physical Verification', type: 'Inventory', generatedOn: '2026-09-30', period: 'Q2 2026', totalIssues: 14, totalReturns: 0, overdueRate: 'N/A', generatedBy: 'Librarian Head' },
  { id: 'rep-003', title: 'Department-wise Book Utilization Summary', type: 'Departmental', generatedOn: '2026-10-05', period: 'Odd Semester 2026-27', totalIssues: 890, totalReturns: 760, overdueRate: '5.2%', generatedBy: 'Dean Academics' },
  { id: 'rep-004', title: 'Overdue Fines & Fee Reconciliation Statement', type: 'Finance', generatedOn: '2026-10-08', period: 'Current Term', totalIssues: 28, totalReturns: 19, overdueRate: '₹4,250 Pending', generatedBy: 'Accounts Office' },
]

export const libraryCategories = [
  'All Categories',
  'Computer Science & AI',
  'Electronics & Communication',
  'Electrical & Power',
  'Mechanical Engineering',
  'Basic Sciences & Mathematics',
  'Reference & Journals',
]

export const libraryDepartments = [
  'All Departments',
  'CSE',
  'AIML',
  'IT',
  'ECE',
  'EEE',
  'MECH',
  'H&S',
]
