import { useEffect, useState } from 'react'
import { FiCheck, FiRefreshCw, FiUserPlus, FiX } from 'react-icons/fi'
import DashboardLayout from '../../layouts/DashboardLayout'
import { approveAccessRequest, getPendingAccessRequests, rejectAccessRequest } from '../../auth/authApi'
import './AccessRequests.css'
import './AccessRequestsEnhancements.css'

const displayDate = value => value ? new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—'

export default function AccessRequests() {
  const [requests, setRequests] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(null), [page, setPage] = useState(1), [pageSize, setPageSize] = useState(5)
  const totalPages = Math.max(1, Math.ceil(requests.length / pageSize)), safePage = Math.min(page, totalPages), visibleRequests = requests.slice((safePage - 1) * pageSize, safePage * pageSize)
  const load = async () => { setLoading(true); setError(''); try { setRequests(await getPendingAccessRequests()); setPage(1) } catch (cause) { setError(cause.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const decide = async (requestId, action) => { setBusy(requestId); setError(''); setNotice(''); try { const result = await (action === 'approve' ? approveAccessRequest : rejectAccessRequest)(requestId); setRequests(current => current.filter(item => item.requestId !== requestId)); setNotice(result?.message || (action === 'approve' ? 'Request approved. The approval email was sent to the applicant.' : 'Request rejected. The rejection email was sent to the applicant.')) } catch (cause) { setError(cause.message || `Unable to ${action} the request. The applicant was not notified.`) } finally { setBusy(null) } }
  useEffect(() => { if (page > totalPages) setPage(totalPages) }, [page, totalPages])
  return <DashboardLayout><main className="access-requests"><header><div><p>Account administration</p><h1>Access Requests</h1><span>Review pending portal-registration requests.</span></div><button onClick={load} disabled={loading}><FiRefreshCw /> Refresh</button></header>{error && <p className="access-requests__error" role="alert">{error}</p>}{notice && <p className="access-requests__notice" role="status">{notice}</p>}<section className="access-requests__card"><div className="access-requests__title"><span><FiUserPlus /></span><div><h2>Pending requests</h2><p>{loading ? 'Loading requests…' : `${requests.length} request${requests.length === 1 ? '' : 's'} awaiting review`}</p></div></div>{!loading && !requests.length ? <div className="access-requests__empty">No pending access requests.</div> : <><div className="access-requests__table"><table><thead><tr><th>Applicant</th><th>Email</th><th>Mobile</th><th>Requested</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visibleRequests.map(item => <tr key={item.requestId}><td><strong>{item.fullName}</strong><small>Request #{item.requestId}</small></td><td>{item.email}</td><td>{item.mobile}</td><td>{displayDate(item.createdAt)}</td><td><span>Pending</span></td><td><div><button type="button" className="approve" disabled={busy === item.requestId} onClick={() => decide(item.requestId, 'approve')}><FiCheck /> {busy === item.requestId ? 'Sending…' : 'Approve'}</button><button type="button" className="reject" disabled={busy === item.requestId} onClick={() => decide(item.requestId, 'reject')}><FiX /> Reject</button></div></td></tr>)}</tbody></table></div><div className="access-requests__pagination"><label htmlFor="access-requests-page-size">Show <select id="access-requests-page-size" value={pageSize} onChange={event => { setPageSize(Number(event.target.value)); setPage(1) }}><option value="5">5</option><option value="10">10</option><option value="25">25</option></select> entries</label><div><button type="button" onClick={() => setPage(current => Math.max(1, current - 1))} disabled={safePage === 1}>Previous</button><span>Page {safePage} of {totalPages}</span><button type="button" onClick={() => setPage(current => Math.min(totalPages, current + 1))} disabled={safePage === totalPages}>Next</button></div></div></>}</section></main></DashboardLayout>
}
