import{useMemo,useState}from'react'
import{FiSave,FiX}from'react-icons/fi'

const clone=value=>structuredClone(value)
const setPath=(source,path,value)=>{const next=clone(source),parts=path.split('.');let cursor=next;parts.slice(0,-1).forEach(key=>{if(!cursor[key])cursor[key]={};cursor=cursor[key]});cursor[parts.at(-1)]=value;return next}
const studentName=student=>[student?.personal?.firstName,student?.personal?.middleName,student?.personal?.lastName].filter(Boolean).join(' ')
const validMobile=value=>/^[6-9]\d{9}$/.test(String(value||''))

export default function StudentProfileEdit({student,onCancel,onSave}){
 const tabs=[['personal','Personal'],['contact','Contact & Address'],['parents','Parent / Guardian'],['academic','Academic'],['education','Previous Education'],['services','Admission & Services']]
 const[form,setForm]=useState(()=>clone(student)),[errors,setErrors]=useState({}),[saving,setSaving]=useState(false),[discard,setDiscard]=useState(false),[tab,setTab]=useState('personal'),original=useMemo(()=>JSON.stringify(student),[student]),dirty=JSON.stringify(form)!==original
 const update=(path,value)=>{setForm(current=>setPath(current,path,value));setErrors(current=>({...current,[path]:''}))},close=()=>{if(saving)return;if(dirty)setDiscard(true);else onCancel()}
 const submit=async event=>{event.preventDefault();const next={};if(!form.personal?.firstName?.trim())next['personal.firstName']='First name is required.';if(!form.personal?.dob)next['personal.dob']='Date of birth is required.';if(!validMobile(form.contact?.mobile))next['contact.mobile']='Enter a valid Indian mobile number.';if(!form.parents?.father?.name?.trim())next['parents.father.name']='Father name is required.';if(!validMobile(form.parents?.father?.mobile))next['parents.father.mobile']='Enter a valid parent mobile number.';setErrors(next);if(Object.keys(next).length){const first=Object.keys(next)[0];setTab(first.startsWith('contact.')?'contact':first.startsWith('parents.')?'parents':'personal');return}setSaving(true);try{await onSave(form)}catch(error){setErrors({form:error?.message||'Unable to update this student.'});setSaving(false)}}
 const Field=({path,label,type='text',required=false,options,readOnly=false})=>{const current=path.split('.').reduce((value,key)=>value?.[key],form)??'',message=errors[path];return <label className={`sp-edit-field ${message?'invalid':''}`}><span>{label}{required&&<b> *</b>}</span>{options?<select value={current} disabled={readOnly} onChange={event=>update(path,event.target.value)}><option value="">Select</option>{options.map(option=><option key={option}>{option}</option>)}</select>:<input type={type} value={current} readOnly={readOnly} onChange={event=>update(path,event.target.value)} inputMode={/mobile|aadhaar|pincode/.test(path)?'numeric':undefined}/>} {message&&<small role="alert">{message}</small>}</label>}
 const fields=rows=><div className="sp-edit-grid">{rows.map(item=><Field key={item[0]} path={item[0]} label={item[1]} {...(item[2]||{})}/>)}</div>
 const addresses=prefix=>fields([['line1','Address line 1'],['line2','Address line 2'],['town','Village / Town'],['city','City'],['district','District'],['state','State'],['country','Country'],['pincode','PIN code']].map(([key,label])=>[`${prefix}.${key}`,label]))
 return <div className="sp-edit-backdrop" onMouseDown={event=>event.target===event.currentTarget&&close()}><section className="sp-edit-dialog" role="dialog" aria-modal="true"><header><div><span>Student management</span><h2>Edit Student Profile</h2><p>Admission details for {studentName(student)||'this student'}.</p></div><button className="sp-close" onClick={close} aria-label="Close"><FiX/></button></header><nav className="sp-edit-tabs" aria-label="Student profile edit sections">{tabs.map(([id,label],index)=><button type="button" key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><i>{index+1}</i>{label}</button>)}</nav><form onSubmit={submit} noValidate>
  {tab==='personal'&&<fieldset><legend>Personal Information</legend>{fields([['personal.firstName','First name',{required:true}],['personal.middleName','Middle name'],['personal.lastName','Last name'],['personal.gender','Gender',{options:['Female','Male','Non-binary']}],['personal.dob','Date of birth',{type:'date',required:true}],['personal.bloodGroup','Blood group',{options:['A+','A-','B+','B-','AB+','AB-','O+','O-']}],['personal.nationality','Nationality'],['personal.aadhaar','Aadhaar number']])}</fieldset>}
  {tab==='contact'&&<><fieldset><legend>Contact Information</legend>{fields([['contact.mobile','Student mobile',{required:true}],['contact.alternateMobile','Alternate mobile'],['contact.email','Student email',{type:'email'}],['contact.alternateEmail','Alternate email',{type:'email'}]])}</fieldset><fieldset><legend>Current Address</legend>{addresses('contact.currentAddress')}</fieldset><fieldset><legend>Permanent Address</legend><label style={{display:'flex',alignItems:'center',gap:'8px',marginBottom:'12px',color:'var(--text-secondary)',fontSize:'12px',fontWeight:600}}><input type="checkbox" checked={Boolean(form.contact?.sameAddress)} onChange={event=>{const checked=event.target.checked;setForm(current=>{const next=clone(current);if(!next.contact)next.contact={};next.contact.sameAddress=checked;if(checked)next.contact.permanentAddress=clone(next.contact.currentAddress||{});return next})}}/><span>Permanent address same as current address</span></label>{!form.contact?.sameAddress&&addresses('contact.permanentAddress')}</fieldset></>}
  {tab==='parents'&&<fieldset><legend>Parent / Guardian</legend>{fields([['parents.father.name','Father name',{required:true}],['parents.father.mobile','Father mobile',{required:true}],['parents.father.email','Father email',{type:'email'}],['parents.father.occupation','Father occupation'],['parents.father.qualification','Father qualification'],['parents.father.income','Father annual income',{type:'number'}],['parents.mother.name','Mother name'],['parents.mother.mobile','Mother mobile'],['parents.guardian.name','Guardian name'],['parents.guardian.relationship','Guardian relationship',{options:['Mother','Brother','Sister','Grandfather','Grandmother','Uncle','Aunt','Legal Guardian','Other']}],['parents.guardian.relationshipOther','Specify relationship'],['parents.guardian.mobile','Guardian mobile'],['parents.primaryContact','Primary contact',{options:['Father','Mother','Guardian']}],['parents.emergencyMobile','Emergency contact']])}</fieldset>}
  {tab==='academic'&&<fieldset><legend>Academic Information</legend><p className="sp-edit-note">Academic placement is system-managed and read-only.</p>{fields([['academic.academicYear','Academic year'],['academic.admissionType','Admission type'],['academic.course','Course'],['academic.department','Department'],['academic.branch','Branch'],['academic.semester','Semester'],['academic.studentCategory','Student category'],['academic.section','Section'],['academic.regulation','Regulation'],['academic.quota','Quota'],['academic.entryType','Entry type']].map(([path,label])=>[path,label,{readOnly:true}]))}</fieldset>}
  {tab==='education'&&<><fieldset><legend>10th / SSC</legend>{fields([['previousEducation.tenth.board','Board'],['previousEducation.tenth.institution','School name'],['previousEducation.tenth.rollNumber','Roll number'],['previousEducation.tenth.passingYear','Year of passing'],['previousEducation.tenth.scoreType','Score type',{options:['Percentage','CGPA']}],['previousEducation.tenth.score','Score',{type:'number'}]])}</fieldset><fieldset><legend>Intermediate / Diploma</legend>{fields([['previousEducation.intermediate.qualification','Qualification',{options:['Intermediate / 12th','Diploma','Equivalent']}],['previousEducation.intermediate.board','Board / University'],['previousEducation.intermediate.institution','College name'],['previousEducation.intermediate.passingYear','Year of passing'],['previousEducation.intermediate.stream','Stream / Specialization'],['previousEducation.intermediate.scoreType','Score type',{options:['Percentage','CGPA']}],['previousEducation.intermediate.score','Score',{type:'number'}]])}</fieldset></>}
  {tab==='services'&&<fieldset><legend>Admission & Services</legend>{fields([['application.registrationNumber','Registration number',{readOnly:true}],['application.admissionNumber','Admission number',{readOnly:true}],['application.admissionDate','Admission date',{type:'date',readOnly:true}],['admission.college','College',{readOnly:true}],['admission.batch','Batch',{readOnly:true}],['admission.scholarship','Scholarship required',{options:['No','Yes']}],['admission.scholarshipType','Scholarship type'],['admission.hostel','Hostel required',{options:['No','Yes']}],['admission.hostelPreference','Hostel preference',{options:['Boys Hostel','Girls Hostel']}],['admission.hostelRoomType','Room type / Beds'],['admission.transport','Transportation required',{options:['No','Yes']}],['admission.transportRoute','Transport route']])}</fieldset>}
  {errors.form&&<p className="sp-form-error" role="alert">{errors.form}</p>}<footer><button type="button" className="sp-button secondary" onClick={close} disabled={saving}>Cancel</button><button type="submit" className="sp-button" disabled={!dirty||saving}>{saving?'Saving...':<><FiSave/> Save Changes</>}</button></footer>
 </form>{discard&&<div className="sp-confirm"><div><h3>You have unsaved changes.</h3><p>Discard your changes?</p><footer><button className="sp-button secondary" onClick={()=>setDiscard(false)}>Stay</button><button className="sp-button danger" onClick={onCancel}>Discard Changes</button></footer></div></div>}</section></div>
}
