import { useCallback, useEffect, useMemo, useState } from 'react'
import { FiCheck, FiEye, FiSearch, FiX } from 'react-icons/fi'
import DashboardLayout from '../../../layouts/DashboardLayout'
import PageHeader from '../../../components/PageHeader'
import MarksModuleNav from './MarksModuleNav'
import FilterPanel from '../../../components/FilterPanel'
import ExportMenu from '../../../components/ExportMenu'
import StatusBadge from '../../../components/StatusBadge'
import ViewDialog from '../../../components/ViewDialog'
import TablePagination from '../../../components/TablePagination'
import EmptyState from '../../../components/EmptyState'
import SearchableSelect from '../../../components/SearchableSelect'
import { useAcademic } from '../../../context/AcademicContext'
import resultsService from '../../../services/resultsService'
import subjectService from '../../../services/subjectService'
import facultyService from '../../../services/facultyService'
import { getExamTypes } from '../../../services/examService'
import studentService from '../../../services/studentService'
import { getUserRole } from '../../../auth/auth'
import { collegeStorageKey } from '../../../utils/collegeScope'
import { showError, showSuccess } from '../../../utils/toast'
import eventBus, { ERP_EVENTS } from '../../../services/eventBus'
import './MarksApproval.css'

const PAGE_SIZE = 10
const approvalColumns=[['subject','Subject'],['subjectCode','Subject Code'],['faculty','Faculty'],['course','Course'],['branch','Branch'],['semester','Semester'],['section','Section'],['exam','Exam'],['totalStudents','Students'],['average','Average Marks'],['submittedAt','Submitted On'],['status','Status']].map(([key,label])=>({key,value:key,label}))
const WORKFLOW_KEY = collegeStorageKey('marks-approval-workflow-v1')
const clean = value => String(value ?? '').trim()
const norm = value => clean(value).toLowerCase().replace(/[_-]+/g,' ')
const semesterNumber = value => { const text=norm(value); const digits=text.match(/\d+/)?.[0]; if(digits)return String(Number(digits)); const roman={i:'1',ii:'2',iii:'3',iv:'4',v:'5',vi:'6',vii:'7',viii:'8'}; return roman[text.replace(/^semester\s*/,'')]||text }
const first = (...values) => values.find(value => value !== undefined && value !== null && clean(value) !== '')
const label = value => value && typeof value === 'object' ? first(value.name,value.label,value.title,value.value,value.academicYearName,value.courseName,value.branchName,value.semesterName,value.sectionName,value.semesterNumber,value.subjectName,value.facultyName,value.fullName,value.examType,'') : value
const sameField = (key,left,right,batch) => key==='semester'?semesterNumber(left)===semesterNumber(right):key==='exam'?(norm(left)===norm(right)||norm(batch?.examType)===norm(right)):norm(left)===norm(right)
const options = (master, rows, keys) => { const values=[...(master||[]).map(item=>label(item)),...(rows||[]).map(row=>keys.map(key=>label(row?.[key])).find(value=>clean(value)))]; return [...new Map(values.map(value=>[norm(value),clean(value)]).filter(([key,value])=>key&&value)).values()].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})) }
const readWorkflow = () => { try { const value=JSON.parse(localStorage.getItem(WORKFLOW_KEY)||'{}'); return value&&typeof value==='object'?value:{} } catch { return {} } }
const writeWorkflow = value => { try { localStorage.setItem(WORKFLOW_KEY,JSON.stringify(value)); window.dispatchEvent(new CustomEvent('marks-approval-updated')) } catch { throw new Error('Approval status could not be saved in this browser.') } }
const getId = (sheet,index) => String(first(sheet.id,sheet.resultId,sheet.resultSheetId,sheet.approvalId,sheet.subjectCode+'-'+sheet.section+'-'+sheet.examType+'-'+index,'submission-'+index))
const getStatus = sheet => { const value=first(sheet.approvalStatus,sheet.approval?.status,sheet.approvalState,sheet.workflowStatus,sheet.reviewStatus,sheet.status); const key=norm(value); if(key==='submitted'||key==='under review')return 'Pending'; return ['pending','approved','rejected','published'].includes(key)?value:'Pending' }
const dateLabel = value => { if(!value)return '—'; const date=new Date(value); return Number.isNaN(date.valueOf())?String(value):new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric'}).format(date) }
const getRoll = student => first(student.rollNumber,student.registrationNumber,student.enrollmentNo,student.admissionNumber,student.studentCode,'')
const getStudentName = student => first(student.studentName,student.name,student.fullName,student.personal?.fullName,student.student?.name,'Student')
const marksValue = student => { const direct=first(student.totalMarks,student.marksObtained,student.obtainedMarks); if(direct!==undefined)return number(direct); const internal=first(student.internalMarks,student.internal,student.internalScore),external=first(student.externalMarks,student.external,student.externalScore); if(internal===undefined&&external===undefined)return null; return (number(internal)||0)+(number(external)||0) }
const number = value => value!==undefined&&value!==null&&clean(value)!==''&&Number.isFinite(Number(value))?Number(value):null
const combinedMaximum = sheet => { const direct=number(first(sheet.maximumMarks,sheet.maxMarks)); if(direct!==null)return direct; const internal=number(sheet.maxInternal),external=number(sheet.maxExternal); return internal!==null||external!==null?(internal||0)+(external||0):'' }
const groupRows = (sheet,index,workflow,studentIndex) => {
  const recordRows=Array.isArray(sheet.records)?sheet.records:[]
  const students=recordRows.map((record,ri)=>{const id=String(first(record.studentId,record.studentProfileId,record.profileId,''));const profile=studentIndex.get(norm(id))||{};const total=marksValue(record);const max=first(record.maximumMarks,combinedMaximum(sheet));const pct=number(max)&&number(total)!==null?Math.round(number(total)/number(max)*100):null;return {id:id||String(ri),rollNumber:first(getRoll(record),getRoll(profile),'—'),studentName:getStudentName(profile.studentId?profile:record),marksObtained:total,maximumMarks:max,percentage:pct===null?'—':pct+'%',grade:first(record.grade,record.resultGrade,'—'),result:first(record.resultStatus,record.status,record.grade==='F'?'Fail':'—')}})
  const totals=students.map(student=>number(student.marksObtained)).filter(value=>value!==null)
  const state=workflow[getId(sheet,index)]||{}
  const approvals=Array.isArray(state.history)?state.history:(Array.isArray(sheet.approvalHistory)?sheet.approvalHistory:[])
  const history=approvals.length?approvals:[{date:first(sheet.submittedAt,sheet.createdAt,sheet.createdDate),user:first(sheet.submittedBy,sheet.facultyName,sheet.faculty,'Faculty'),action:'Submitted',remarks:'—'}]
  const subject=first(sheet.subjectName,sheet.subject,sheet.courseSubject,'—'), subjectCode=first(sheet.subjectCode,sheet.code,'—')
  return { id:getId(sheet,index), source:sheet, subject,subjectCode,faculty:label(first(sheet.facultyName,sheet.faculty?.name,sheet.faculty,sheet.createdByName,'—')), academicYear:label(first(sheet.academicYear,sheet.academicYearName,sheet.yearName,'')), course:label(first(sheet.course,sheet.courseName,'')), branch:label(first(sheet.branch,sheet.branchName,sheet.department,'')), semester:label(first(sheet.semester,sheet.semesterName,'')), section:label(first(sheet.section,sheet.sectionName,'')), exam:first(sheet.examName,sheet.examinationName,sheet.examType,sheet.exam,'—'), examType:first(sheet.examType,sheet.examName,''), maximumMarks:first(combinedMaximum(sheet),'—'), passingMarks:first(sheet.passingMarks,sheet.minimumPassingMarks,'—'), submittedAt:first(sheet.submittedAt,sheet.submissionDate,sheet.createdAt,sheet.createdDate,''),status:state.status||getStatus(sheet), approvedBy:state.approvedBy||sheet.approvedBy||sheet.approval?.approvedBy||'', approvedAt:state.approvedAt||sheet.approvedAt||sheet.approval?.approvedAt||'', remarks:state.remarks||sheet.rejectionReason||sheet.approvalRemarks||'',history,students,totalStudents:students.length||Number(sheet.totalStudents)||0,average:totals.length?(totals.reduce((a,b)=>a+b,0)/totals.length):number(sheet.averageMarks),highest:totals.length?Math.max(...totals):number(sheet.highestMarks),lowest:totals.length?Math.min(...totals):number(sheet.lowestMarks),passed:students.filter(row=>norm(row.result).includes('pass')||(!row.result||row.result==='—')&&number(row.marksObtained)!==null&&number(row.marksObtained)>=number(sheet.passingMarks)).length,failed:students.filter(row=>norm(row.result).includes('fail')).length }
}
const approverRoles=new Set(['admin','college_admin','super_admin','hod','department_head','exam_cell','examcell','exam_officer','exam_office'])
const currentUser=()=>{try{return localStorage.getItem('btech-user-name')||sessionStorage.getItem('btech-user-name')||'Current user'}catch{return 'Current user'}}

function DecisionDialog({kind,batch,onCancel,onConfirm,busy}) {
  const [remarks,setRemarks]=useState('')
  const reject=kind==='reject'
  const submit=event=>{event.preventDefault();if(reject&&!remarks.trim())return;onConfirm(remarks.trim())}
  return <div className="marks-approval-dialog-backdrop" role="presentation" onMouseDown={event=>event.target===event.currentTarget&&!busy&&onCancel()}><section className="marks-approval-decision" role="alertdialog" aria-modal="true" aria-labelledby="marks-approval-decision-title"><button className="marks-approval-decision__close" type="button" aria-label="Close" onClick={onCancel} disabled={busy}><FiX/></button><div className={'marks-approval-decision__icon '+(reject?'is-reject':'')} aria-hidden="true">{reject?<FiX/>:<FiCheck/>}</div><h2 id="marks-approval-decision-title">{reject?'Reject Marks':'Approve Marks'}</h2><p>{reject?'Review this submission and provide a reason for rejection.':'Please confirm the submitted marks after review.'}</p><dl><div><dt>Subject</dt><dd>{batch.subject}</dd></div><div><dt>Subject Code</dt><dd>{batch.subjectCode}</dd></div><div><dt>Faculty</dt><dd>{batch.faculty}</dd></div><div><dt>Exam</dt><dd>{batch.exam}</dd></div><div><dt>Students</dt><dd>{batch.totalStudents}</dd></div></dl><form onSubmit={submit}><label>{reject?'Rejection Reason *':'Approval Remarks (optional)'}<textarea rows="3" value={remarks} onChange={event=>setRemarks(event.target.value)} required={reject} placeholder={reject?'Explain what needs correction':'Add a note for the approval history'}/></label><footer><button className="erp-btn erp-btn--secondary" type="button" onClick={onCancel} disabled={busy}>Cancel</button><button className={'erp-btn '+(reject?'erp-btn--danger':'erp-btn--primary')} type="submit" disabled={busy||(reject&&!remarks.trim())}>{busy?(reject?'Rejecting marks…':'Approving marks…'):(reject?'Reject Marks':'Confirm Approval')}</button></footer></form></section></div>
}

export default function MarksApproval() {
  const academic=useAcademic()
  const role=getUserRole()||''
  const facultyUser=role==='faculty'
  const canDecide=approverRoles.has(role)
  const forbidden=role==='student'
  const [sheets,setSheets]=useState([]),[students,setStudents]=useState([]),[subjectCatalog,setSubjectCatalog]=useState([]),[facultyCatalog,setFacultyCatalog]=useState([]),[examCatalog]=useState(()=>{try{return getExamTypes()}catch{return []}}),[workflow,setWorkflow]=useState(readWorkflow),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[search,setSearch]=useState(''),[statusFilter,setStatusFilter]=useState('All'),[appliedStatus,setAppliedStatus]=useState('All'),[filters,setFilters]=useState({academicYear:'',course:'',branch:'',semester:'',subject:'',exam:'',faculty:''}),[applied,setApplied]=useState(null),[page,setPage]=useState(1),[selected,setSelected]=useState(null),[decision,setDecision]=useState(''),[busy,setBusy]=useState(false)
  const load=useCallback(async()=>{if(forbidden){setLoading(false);return}setLoading(true);setLoadError('');try{const [resultResponse,profileResponse]=await Promise.allSettled([resultsService.getResults(),studentService.getAllProfiles()]);if(resultResponse.status==='rejected')throw resultResponse.reason;setSheets(Array.isArray(resultResponse.value)?resultResponse.value:[]);setStudents(profileResponse.status==='fulfilled'&&Array.isArray(profileResponse.value)?profileResponse.value:[]);if(profileResponse.status==='rejected')setLoadError('Student profile data is unavailable; student names may be incomplete.');setWorkflow(readWorkflow())}catch(error){setLoadError(error?.message||'Marks submissions could not be loaded. Please retry.');showError(error)}finally{setLoading(false)}},[forbidden])
  useEffect(()=>{load();const refresh=()=>load();const unsubscribe=eventBus.subscribe(ERP_EVENTS.RESULTS_RECORDED,refresh);const changed=()=>{setWorkflow(readWorkflow());load()};window.addEventListener('marks-approval-updated',changed);window.addEventListener('focus',refresh);return()=>{unsubscribe();window.removeEventListener('marks-approval-updated',changed);window.removeEventListener('focus',refresh)}},[load])
  useEffect(()=>{let active=true;Promise.allSettled([subjectService.getSubjects({liveOnly:true}),facultyService.list()]).then(([subjects,faculty])=>{if(!active)return;if(subjects.status==='fulfilled')setSubjectCatalog(Array.isArray(subjects.value)?subjects.value:[]);if(faculty.status==='fulfilled')setFacultyCatalog(Array.isArray(faculty.value)?faculty.value:[])});return()=>{active=false}},[])
  const studentIndex=useMemo(()=>{const map=new Map();students.forEach(s=>[s.studentId,s.id,s.registrationNumber,s.application?.registrationNumber,s.academic?.rollNumber].filter(Boolean).forEach(id=>map.set(norm(id),s)));return map},[students])
  const batches=useMemo(()=>sheets.map((sheet,index)=>groupRows(sheet,index,workflow,studentIndex)),[sheets,workflow,studentIndex])
  const masters={academicYear:academic.academicYears,course:academic.courses,branch:academic.branches,semester:academic.semesters,section:academic.sections}
  const subjectOptions=useMemo(()=>{const found=new Map();[...subjectCatalog,...batches.map(batch=>({subjectName:batch.subject,subjectCode:batch.subjectCode}))].forEach(item=>{const name=clean(first(item.subjectName,item.name,item.label,item.subject)),code=clean(first(item.subjectCode,item.code,''));if(name){const key=norm(name);if(!found.has(key))found.set(key,{value:name,label:name,code})}});return [...found.values()].sort((a,b)=>a.label.localeCompare(b.label))},[subjectCatalog,batches])
  const filterOptions={academicYear:options(masters.academicYear,batches,['academicYear']),course:options(masters.course,batches,['course']),branch:options(masters.branch,batches,['branch']),semester:Array.from({length:8},(_,index)=>'Semester '+(index+1)),subject:subjectOptions,exam:options(examCatalog,batches,['exam','examType']),faculty:options(facultyCatalog,batches,['faculty'])}
  const facultyName=currentUser()
  const inScope=useMemo(()=>batches.filter(batch=>!facultyUser||norm(batch.faculty)===norm(facultyName)),[batches,facultyUser,facultyName])
  const baseRows=useMemo(()=>inScope.filter(batch=>!applied||Object.entries(applied).every(([key,value])=>!value||sameField(key,batch[key],value,batch))),[inScope,applied])
  const rows=useMemo(()=>baseRows.filter(batch=>(appliedStatus==='All'||norm(batch.status)===norm(appliedStatus))&&(!search.trim()||[batch.subject,batch.subjectCode,batch.faculty].some(value=>norm(value).includes(norm(search))))),[baseRows,appliedStatus,search])
  const countRows=baseRows
  const counts={total:countRows.length,pending:countRows.filter(row=>norm(row.status)==='pending'||norm(row.status)==='submitted').length,approved:countRows.filter(row=>norm(row.status)==='approved').length,rejected:countRows.filter(row=>norm(row.status)==='rejected').length}
  const visible=rows.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE)
  const applyFilters=event=>{event.preventDefault();if(!filters.academicYear||!filters.course||!filters.branch||!filters.semester){showError('Select Academic Year, Course, Branch and Semester before applying filters.');return}setApplied({...filters});setAppliedStatus(statusFilter);setPage(1)}
  const resetFilters=()=>{const empty={academicYear:'',course:'',branch:'',semester:'',subject:'',exam:'',faculty:''};setFilters(empty);setApplied(null);setSearch('');setStatusFilter('All');setAppliedStatus('All');setPage(1)}
  const decisionFor=(batch,kind)=>{setSelected(batch);setDecision(kind)}
  const confirmDecision=remarks=>{if(!selected||!canDecide||norm(selected.status)!=='pending')return;setBusy(true);try{const now=new Date().toISOString(),action=decision==='approve'?'Approved':'Rejected',entry={date:now,user:currentUser(),action,remarks:remarks||'—'};const next={...workflow,[selected.id]:{status:action,history:[...selected.history,entry],...(decision==='approve'?{approvedBy:currentUser(),approvedAt:now,remarks}:{rejectionReason:remarks})}};writeWorkflow(next);setWorkflow(next);setDecision('');setSelected(current=>current?{...current,status:action,history:[...current.history,entry],...(decision==='approve'?{approvedBy:currentUser(),approvedAt:now,remarks}:{remarks})}:null);showSuccess(decision==='approve'?'Marks approved successfully.':'Marks rejected successfully.')}catch(error){showError(error)}finally{setBusy(false)}}
  const allOptions=(values,key)=>values.map(value=>typeof value==='object'?value:{value,label:key==='semester'&&/^\d+$/.test(semesterNumber(value))?'Semester '+semesterNumber(value):value})
  const setField=(key,value)=>setFilters(current=>({...current,[key]:value}))
  const formatAverage=batch=>batch.average===null?'—':Number(batch.average).toFixed(1)+' / '+batch.maximumMarks
  const statusTag=status=><StatusBadge value={status}/>
  const detailFields=selected?[['Subject',selected.subject],['Subject Code',selected.subjectCode],['Faculty',selected.faculty],['Course',selected.course],['Branch',selected.branch],['Academic Year',selected.academicYear],['Semester',selected.semester],['Section',selected.section||'—'],['Exam',selected.exam],['Maximum Marks',selected.maximumMarks],['Passing Marks',selected.passingMarks],['Submitted Date',dateLabel(selected.submittedAt)],['Current Status',statusTag(selected.status)],...(selected.approvedBy?[['Approved By',selected.approvedBy],['Approved Date',dateLabel(selected.approvedAt)]]:[]),...(norm(selected.status)==='rejected'?[['Rejection Reason',selected.remarks||'—']]:[])]:[]
  return <DashboardLayout><section className="marks-management-marks-approval"><PageHeader title="Marks Approval" breadcrumb={[{label:'Marks Management',link:'/marks-management'},'Marks Approval']}/><MarksModuleNav/><header className="marks-approval-intro"><h2>Marks Approval</h2><p>Review, verify and approve submitted student marks.</p></header>
    {forbidden?<article className="erp-card marks-approval-forbidden"><EmptyState title="Access restricted" description="Students cannot access Marks Approval."/></article>:<>
    <section className="marks-approval-summary" aria-label="Submission summary">{[['Total Submissions',counts.total,'total'],['Pending',counts.pending,'pending'],['Approved',counts.approved,'approved'],['Rejected',counts.rejected,'rejected']].map(([title,value,tone])=><article className={'erp-card marks-approval-stat marks-approval-stat--'+tone} key={title}><span>{title}</span><strong>{value}</strong></article>)}</section>
    <article className="erp-card marks-approval-filter-card"><form onSubmit={applyFilters}><FilterPanel className="marks-approval-filter-panel" active={Boolean(applied&&Object.values(applied).some(Boolean)||appliedStatus!=='All')} onClear={resetFilters} hideClear leadingActions={<ExportMenu rows={rows} columns={approvalColumns} title="Marks Approval" filename="marks-approval-submissions" scope="Filtered submissions" allowEmpty/>}>
      <div className="marks-approval-filter-layout"><label className="marks-approval-filter-search"><FiSearch aria-hidden="true"/><input type="search" aria-label="Search marks submissions" placeholder="Search subject, subject code or faculty" value={search} onChange={event=>{setSearch(event.target.value);setPage(1)}}/></label><div className="marks-approval-dropdown-grid">
      {['academicYear','course','branch','semester','subject','exam','faculty'].map(key=><div className="marks-approval-filter" key={key}><span className="marks-approval-filter-label">{{academicYear:'Academic Year *',course:'Course *',branch:'Branch *',semester:'Semester *',subject:'Subject',exam:'Exam',faculty:'Faculty'}[key]}</span><SearchableSelect label={{academicYear:'Academic Year *',course:'Course *',branch:'Branch *',semester:'Semester *',subject:'Subject',exam:'Exam',faculty:'Faculty'}[key]} value={filters[key]} options={allOptions(filterOptions[key],key)} onChange={value=>setField(key,value)} placeholder={'All '+({academicYear:'academic years',course:'courses',branch:'branches',semester:'semesters',subject:'subjects',exam:'exams',faculty:'faculty'}[key])} searchPlaceholder={'Search '+key}/></div>)}
      <label className="marks-approval-filter marks-approval-status-filter"><span>Status</span><select value={statusFilter} onChange={event=>{setStatusFilter(event.target.value);setPage(1)}}><option>All</option><option>Pending</option><option>Approved</option><option>Rejected</option></select></label><div className="marks-approval-filter-actions"><button className="erp-btn erp-btn--primary" type="submit">Apply Filters</button></div>
      </div></div>
    </FilterPanel></form></article>
    <article className="erp-card marks-approval-table-card"><header className="erp-card-header"><div><h2 className="erp-card-title">Submitted Marks</h2><p className="erp-card-subtitle">{rows.length} submission{rows.length===1?'':'s'} match the current filters.</p></div></header>
      {loadError&&<div className="marks-approval-error" role="alert"><span>{loadError}</span><button type="button" className="erp-btn erp-btn--secondary" onClick={load}>Retry</button></div>}
      {loading?<p className="marks-approval-loading" role="status">Loading submissions...</p>:!rows.length?<EmptyState title="No marks submissions found." description="Try changing your filters or check whether faculty have submitted marks."/>:<div className="marks-approval-table-wrap"><table className="erp-table marks-approval-table"><thead><tr>{['Subject','Subject Code','Faculty','Course','Branch','Semester','Section','Exam','Students','Average Marks','Submitted On','Status','Action'].map(col=><th key={col}>{col}</th>)}</tr></thead><tbody>{visible.map(batch=><tr key={batch.id}><td>{batch.subject}</td><td>{batch.subjectCode}</td><td>{batch.faculty}</td><td>{batch.course||'—'}</td><td>{batch.branch||'—'}</td><td>{batch.semester||'—'}</td><td>{batch.section||'—'}</td><td>{batch.exam}</td><td>{batch.totalStudents}</td><td>{formatAverage(batch)}</td><td>{dateLabel(batch.submittedAt)}</td><td>{statusTag(batch.status)}</td><td><button type="button" className="marks-approval-view-btn" onClick={()=>setSelected(batch)}><FiEye aria-hidden="true"/> View</button></td></tr>)}</tbody></table></div>}
      {!loading&&rows.length>PAGE_SIZE&&<TablePagination currentPage={page} totalPages={Math.ceil(rows.length/PAGE_SIZE)} onPageChange={setPage}/>}
    </article>
    {selected&&<ViewDialog title="Marks Approval Details" subtitle={selected.subject+' · '+selected.subjectCode} onClose={()=>setSelected(null)} maxWidth="1100px" footerActions={canDecide&&norm(selected.status)==='pending'?<><button className="erp-btn erp-btn--danger" type="button" onClick={()=>decisionFor(selected,'reject')}>Reject</button><button className="erp-btn erp-btn--primary" type="button" onClick={()=>decisionFor(selected,'approve')}>Approve</button></>:null}>
      <dl className="marks-approval-details-grid">{detailFields.map(([name,value])=><div key={name}><dt>{name}</dt><dd>{value}</dd></div>)}</dl>
      <div className="marks-approval-detail-summary">{[['Total Students',selected.totalStudents],['Average Marks',selected.average===null?'—':Number(selected.average).toFixed(1)],['Highest Marks',selected.highest??'—'],['Lowest Marks',selected.lowest??'—'],['Passed',selected.passed],['Failed',selected.failed]].map(([name,value])=><div key={name}><small>{name}</small><strong>{value}</strong></div>)}</div>
      {norm(selected.status)==='rejected'&&<p className="marks-approval-rejection-note"><strong>Rejection reason:</strong> {selected.remarks||'—'} Faculty can correct marks from the existing Edit Marks screen and resubmit.</p>}
      <h3 className="marks-approval-section-title">Student Marks Review</h3>{selected.students.length?<div className="marks-approval-students-wrap"><table className="erp-table marks-approval-students"><thead><tr>{['Roll Number','Student Name','Marks Obtained','Maximum Marks','Percentage','Grade','Result'].map(col=><th key={col}>{col}</th>)}</tr></thead><tbody>{selected.students.map(row=><tr key={row.id}><td>{row.rollNumber}</td><td>{row.studentName}</td><td>{row.marksObtained??'—'}</td><td>{row.maximumMarks??selected.maximumMarks}</td><td>{row.percentage}</td><td>{row.grade}</td><td>{row.result}</td></tr>)}</tbody></table></div>:<EmptyState title="Student marks are unavailable" description="This submission does not include individual student records."/>}
      <h3 className="marks-approval-section-title">Approval History</h3><ol className="marks-approval-history">{selected.history.map((entry,index)=><li key={index}><span className="marks-approval-history__dot"/><div><div className="marks-approval-history__head"><strong>{first(entry.action,entry.status,'Updated')}</strong><time>{dateLabel(first(entry.date,entry.createdAt))}</time></div><p>{first(entry.user,entry.userName,entry.approvedBy,'—')} {entry.remarks&&entry.remarks!=='—'?'· '+entry.remarks:''}</p></div></li>)}</ol>
      <div className="marks-approval-workflow" aria-label="Marks status workflow"><span>Draft</span><i>→</i><span>Submitted</span><i>→</i><span className={norm(selected.status)==='pending'?'is-current':''}>Pending</span><i>→</i><span className={norm(selected.status)==='approved'?'is-current':''}>{norm(selected.status)==='approved'?'Approved':'Approved / Rejected'}</span><i>→</i><span>Published</span></div>
    </ViewDialog>}
    {decision&&selected&&<DecisionDialog key={decision+selected.id} kind={decision} batch={selected} onCancel={()=>setDecision('')} onConfirm={confirmDecision} busy={busy}/>}
    </>}
  </section></DashboardLayout>
}
