import { useMemo, useState } from 'react'
import DashboardLayout from '../../layouts/DashboardLayout'
import './DepartmentManagement.css'

const seed = [
  ['Computer Science & Engineering', 'CSE', 'Dr. Anjali Sharma', 'B.Tech'], ['CSE AI & ML', 'CSE-AIML', 'Dr. Rohan Verma', 'B.Tech'], ['CSE Data Science', 'CSE-DS', 'Not assigned', 'B.Tech'], ['Electronics & Communication Engineering', 'ECE', 'Dr. Priya Nair', 'B.Tech'], ['Electrical & Electronics Engineering', 'EEE', 'Not assigned', 'B.Tech'], ['Mechanical Engineering', 'MECH', 'Not assigned', 'B.Tech'], ['Civil Engineering', 'CIVIL', 'Not assigned', 'B.Tech'], ['B.Sc Computers', 'BSC-COMP', 'Not assigned', 'Degree'], ['B.Com General', 'BCOM-GEN', 'Not assigned', 'Degree'], ['B.Com Computers', 'BCOM-COMP', 'Not assigned', 'Degree'], ['BBA', 'BBA', 'Not assigned', 'Degree'], ['BA', 'BA', 'Not assigned', 'Degree'],
].map(([name, code, hod, type], index) => ({ id: index + 1, name, code, hod, type, status: index === 4 ? 'Inactive' : 'Active', description: `${type} programme for ${name}.` }))
const empty = { name: '', code: '', hod: '', description: '', type: 'B.Tech', status: 'Active' }

export default function DepartmentManagement() {
  const [items, setItems] = useState(seed), [screen, setScreen] = useState('list'), [selected, setSelected] = useState(null), [form, setForm] = useState(empty), [query, setQuery] = useState(''), [type, setType] = useState('All'), [error, setError] = useState('')
  const visible = useMemo(() => items.filter((item) => `${item.name} ${item.code} ${item.hod}`.toLowerCase().includes(query.toLowerCase()) && (type === 'All' || item.type === type)), [items, query, type])
  const edit = (item) => { setSelected(item); setForm({ ...item }); setError(''); setScreen('form') }
  const details = (item) => { setSelected(item); setScreen('details') }
  const toggleStatus = (item) => { const changed = { ...item, status: item.status === 'Active' ? 'Inactive' : 'Active' }; setItems((all) => all.map((entry) => entry.id === item.id ? changed : entry)); if (selected?.id === item.id) setSelected(changed) }
  const save = (event) => { event.preventDefault(); const code = form.code.trim().toUpperCase(); if (!form.name.trim() || !code) return setError('Department name and department code are required.'); if (items.some((item) => item.code === code && item.id !== form.id)) return setError('This department code already exists.'); const next = { ...form, name: form.name.trim(), code, hod: form.hod.trim() || 'Not assigned', description: form.description.trim() }; setItems((all) => form.id ? all.map((item) => item.id === form.id ? next : item) : [...all, { ...next, id: Date.now() }]); setScreen('list') }
  const assignHod = (event) => { event.preventDefault(); if (!form.hod.trim()) return setError('Enter the Head of Department name.'); const next = { ...selected, hod: form.hod.trim() }; setItems((all) => all.map((item) => item.id === next.id ? next : item)); setSelected(next); setScreen('details') }
  const field = (name, label, extra = {}) => <label>{label}<input value={form[name]} onChange={(event) => setForm({ ...form, [name]: event.target.value })} {...extra} /></label>
  return <DashboardLayout><div className="management-page department-management"><div className="management-page__heading"><div><p className="management-page__eyebrow">Administration</p><h1>Department Management</h1><p>This module manages all college departments.</p></div>{screen === 'list' && <button onClick={() => { setForm(empty); setError(''); setScreen('form') }}>+ Add Department</button>}</div>
    {screen === 'list' && <section className="management-card department-list"><div className="department-list__top"><div><h2>Department List</h2><p>{visible.length} departments shown</p></div><div className="department-controls"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name, code or HOD" /><select value={type} onChange={(event) => setType(event.target.value)}><option>All</option><option>B.Tech</option><option>Degree</option></select></div></div><div className="department-table-wrap"><table><thead><tr><th>Department</th><th>Code</th><th>Programme</th><th>HOD</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visible.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><span>{item.description}</span></td><td>{item.code}</td><td>{item.type}</td><td>{item.hod}</td><td><button className={`status-pill ${item.status.toLowerCase()}`} onClick={() => toggleStatus(item)}>{item.status}</button></td><td className="row-actions"><button onClick={() => details(item)}>View</button><button onClick={() => edit(item)}>Edit</button></td></tr>)}</tbody></table></div>{!visible.length && <p className="department-no-results">No departments match your search.</p>}</section>}
    {screen === 'form' && <section className="management-card department-form-card"><Header title={form.id ? 'Edit Department' : 'Add Department'} subtitle="Enter the department information below." back={() => setScreen('list')} /><form onSubmit={save}><div className="department-form-grid">{field('name', 'Department Name', { placeholder: 'e.g. Computer Science & Engineering' })}{field('code', 'Department Code', { placeholder: 'e.g. CSE' })}<label>Programme<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}><option>B.Tech</option><option>Degree</option></select></label><label>Status<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option>Active</option><option>Inactive</option></select></label><label className="full-width">HOD<input value={form.hod} onChange={(event) => setForm({ ...form, hod: event.target.value })} placeholder="Enter Head of Department name" /></label><label className="full-width">Description<textarea rows="4" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Brief department description" /></label></div>{error && <p className="department-error">{error}</p>}<Actions cancel={() => setScreen('list')} submit={form.id ? 'Save Changes' : 'Create Department'} /></form></section>}
    {screen === 'details' && selected && <section className="management-card department-details"><Header title={selected.name} subtitle={`${selected.code} · ${selected.type}`} back={() => setScreen('list')} /><div className="detail-grid"><div><span>Department Code</span><strong>{selected.code}</strong></div><div><span>Status</span><button className={`status-pill ${selected.status.toLowerCase()}`} onClick={() => toggleStatus(selected)}>{selected.status}</button></div><div><span>Head of Department</span><strong>{selected.hod}</strong></div><div><span>Programme</span><strong>{selected.type}</strong></div><div className="detail-description"><span>Description</span><p>{selected.description || 'No description added.'}</p></div></div><div className="detail-actions"><button onClick={() => { setForm({ hod: selected.hod === 'Not assigned' ? '' : selected.hod }); setError(''); setScreen('hod') }}>Assign HOD</button><button className="secondary-button" onClick={() => edit(selected)}>Edit Department</button></div></section>}
    {screen === 'hod' && selected && <section className="management-card hod-card"><Header title="Assign HOD" subtitle={`Assign a Head of Department for ${selected.name}.`} back={() => setScreen('details')} /><form onSubmit={assignHod}>{field('hod', 'Head of Department', { autoFocus: true, placeholder: 'Enter HOD name' })}{error && <p className="department-error">{error}</p>}<Actions cancel={() => setScreen('details')} submit="Assign HOD" /></form></section>}
  </div></DashboardLayout>
}
function Header({ title, subtitle, back }) { return <div className="screen-title"><div><h2>{title}</h2><p>{subtitle}</p></div><button className="secondary-button" onClick={back}>Back to List</button></div> }
function Actions({ cancel, submit }) { return <div className="form-actions"><button type="button" className="secondary-button" onClick={cancel}>Cancel</button><button type="submit">{submit}</button></div> }
